CREATE TABLE IF NOT EXISTS `item_upgrade_chain` (
  `entry` int unsigned NOT NULL COMMENT 'current entry being upgraded FROM (PK)',
  `origin_entry` int unsigned NOT NULL DEFAULT '0' COMMENT 'base entry of the line (Quality of base)',
  `from_quality` tinyint unsigned NOT NULL DEFAULT '0' COMMENT 'Quality of entry',
  `to_quality` tinyint unsigned NOT NULL DEFAULT '0' COMMENT 'Quality of next tier (= from_quality + 1)',
  `step` tinyint unsigned NOT NULL DEFAULT '0' COMMENT 'tiers above the original (= to_quality - base quality); bonus driver',
  `next_entry` int unsigned NOT NULL DEFAULT '0' COMMENT 'entry of next tier (success target); 0 = ceiling',
  `prev_entry` int unsigned NOT NULL DEFAULT '0' COMMENT 'entry of previous tier (downgrade target); 0 = base',
  `bonus_pct` smallint unsigned NOT NULL DEFAULT '0' COMMENT 'bonus of next_entry (= 10 * step)',
  `kit_profession` varchar(16) NOT NULL DEFAULT '' COMMENT 'required kit: blacksmith/leather/tailor/jewel',
  `kit_tier` tinyint unsigned NOT NULL DEFAULT '0' COMMENT 'kit tier = to_quality (2 green / 3 blue / 4 purple)',
  `nemesis_rank` int unsigned NOT NULL DEFAULT '0' COMMENT 'min Nemesis rank (by to_quality). PLACEHOLDER 0 - TODO(nemesis-dev)',
  `success_pct` tinyint unsigned NOT NULL DEFAULT '0' COMMENT 'success chance (by to_quality: 95/75/50)',
  `gold_cost` int unsigned NOT NULL DEFAULT '0' COMMENT 'optional gold cost per attempt (copper)',
  `fail_downgrade` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '1 only when to_quality = 4 (purple step downgrades on fail)',
  PRIMARY KEY (`entry`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Gear Ascension upgrade edges (generated by mod-gear-ascension generator)';
