#Requires -Version 5.1
<#
.SYNOPSIS
    Apply: Gear Ascension -> live server (acore_world)
    Package: 2026-06-20_1200-gear-ascension

.DESCRIPTION
    Human-run script. Applies the full Gear Ascension feature set to production acore_world.
    Performs no writes until explicit confirmation prompts are answered.

    Apply order:
      Step 1  Pre-flight safety checks
      Step 2  Snapshot acore_world -> pre-deploy-snapshot.sql.gz
      Step 3  CREATE item_upgrade_chain table if absent
      Step 4  Apply 6 SQL files to acore_world (in dependency order)
      Step 5  Post-apply verification queries
      Step 6  Build live worldserver image (optional -- human confirms)
      Step 7  Worldserver restart is DEFERRED -- instructions printed only

    IMPORTANT: Do NOT run while players are actively upgrading items mid-cast.
    The DB apply itself is safe with the server running (inert until restart).
    Stop ac-worldserver-ptr before the image build step to free WSL2 RAM.

    Non-DB actions NOT performed by this script (human must do manually):
      - Edit env\dist\etc\modules\mod_ahbot.conf (AHBot item ID restriction)
      - Distribute client MPQ patch to players (Item.dbc + ItemExtendedCost.dbc + Spell.dbc)
      - Restart ac-worldserver-v2 (deferred per owner decision)

.NOTES
    Agent permission policy: this script is USER-RUN, NOT agent-run.
    The agent prepared this package but does not execute it.
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# --- Config ---
$REPO_ROOT      = "D:\Projects\Wow\v2\azerothcore-wotlk-playerbots\azerothcore-wotlk"
$DB_CONTAINER   = "ac-database-v2"
$WS_CONTAINER   = "ac-worldserver-v2"
$DB_USER        = "root"
$DB_PASS        = if ($env:DOCKER_DB_ROOT_PASSWORD) { $env:DOCKER_DB_ROOT_PASSWORD } else { "password" }
$WORLD_DB       = "acore_world"

$PKG_DIR        = "$REPO_ROOT\.claude\agent-memory\live-deployer\packages\2026-06-20_1200-gear-ascension"
$SNAPSHOT_FILE  = "$PKG_DIR\pre-deploy-snapshot.sql.gz"

# SQL files in dependency order
$WORLD_SQL = @(
    "$REPO_ROOT\data\sql\updates\pending_db_world\gear_ascension_cleanup_1m_block.sql",
    "$REPO_ROOT\data\sql\updates\pending_db_world\gear_ascension_kits.sql",
    "$REPO_ROOT\data\sql\updates\pending_db_world\gear_ascension_polish_a.sql",
    "$REPO_ROOT\data\sql\updates\pending_db_world\gear_ascension_proto.sql",
    "$REPO_ROOT\data\sql\updates\pending_db_world\gear_ascension_white_bases.sql",
    "$REPO_ROOT\data\sql\updates\pending_db_world\gear_ascension_kit_vendor.sql"
)

# item_upgrade_chain DDL (must match PTR schema)
$CHAIN_DDL = @"
CREATE TABLE IF NOT EXISTS ``item_upgrade_chain`` (
  ``entry``          int unsigned NOT NULL COMMENT 'current entry being upgraded FROM (PK)',
  ``origin_entry``   int unsigned NOT NULL DEFAULT '0' COMMENT 'base entry of the line',
  ``from_quality``   tinyint unsigned NOT NULL DEFAULT '0' COMMENT 'Quality of entry',
  ``to_quality``     tinyint unsigned NOT NULL DEFAULT '0' COMMENT 'Quality of next tier',
  ``step``           tinyint unsigned NOT NULL DEFAULT '0' COMMENT 'tiers above the original',
  ``next_entry``     int unsigned NOT NULL DEFAULT '0' COMMENT 'entry of next tier; 0 = ceiling',
  ``prev_entry``     int unsigned NOT NULL DEFAULT '0' COMMENT 'entry of previous tier; 0 = base',
  ``bonus_pct``      smallint unsigned NOT NULL DEFAULT '0' COMMENT 'stat bonus pct of next_entry',
  ``kit_profession`` varchar(16) NOT NULL DEFAULT '' COMMENT 'required kit category',
  ``kit_tier``       tinyint unsigned NOT NULL DEFAULT '0' COMMENT 'required kit tier (2/3/4)',
  ``nemesis_rank``   int unsigned NOT NULL DEFAULT '0' COMMENT 'min Nemesis rank required',
  ``success_pct``    tinyint unsigned NOT NULL DEFAULT '0' COMMENT 'success chance pct',
  ``gold_cost``      int unsigned NOT NULL DEFAULT '0' COMMENT 'optional gold cost in copper',
  ``fail_downgrade`` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '1 when to_quality=4 (purple fail downgrades)',
  PRIMARY KEY (``entry``)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='Gear Ascension upgrade edges (generated by mod-gear-ascension generator)';
"@

# --- Helper functions ---
function Confirm-Step {
    param([string]$Message)
    Write-Host ""
    Write-Host $Message -ForegroundColor Yellow
    $reply = Read-Host "Continue? (yes/skip/abort)"
    if ($reply -eq "abort") { Write-Host "Aborted by user." -ForegroundColor Red; exit 1 }
    return ($reply -eq "yes")
}

function Invoke-LiveQuery {
    param([string]$Query)
    docker exec $DB_CONTAINER mysql -u $DB_USER -p$DB_PASS --default-character-set=utf8mb4 -N -e $Query $WORLD_DB 2>$null
}

function Apply-SqlFile {
    param([string]$FilePath, [string]$Label = "")
    $filename = Split-Path $FilePath -Leaf
    $display = if ($Label) { "$filename ($Label)" } else { $filename }
    Write-Host "  Applying: $display ..." -NoNewline
    # Stream via stdin to handle large files without hitting command-line length limits
    $result = & docker exec -i $DB_CONTAINER mysql -u $DB_USER -p$DB_PASS --default-character-set=utf8mb4 --max_allowed_packet=512M $WORLD_DB 2>&1 < $FilePath
    if ($LASTEXITCODE -ne 0) {
        Write-Host " FAILED" -ForegroundColor Red
        Write-Host "  Error output: $result" -ForegroundColor Red
        throw "SQL apply failed for $filename"
    }
    Write-Host " OK" -ForegroundColor Green
}

# ============================================================
# STEP 1: Pre-flight checks
# ============================================================
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host " STEP 1: Pre-flight checks" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan

# DB container running?
$dbStatus = docker inspect --format "{{.State.Running}}" $DB_CONTAINER 2>$null
if ($dbStatus -ne "true") {
    Write-Host "FAIL: DB container '$DB_CONTAINER' is not running." -ForegroundColor Red
    exit 1
}
Write-Host "OK: DB container $DB_CONTAINER is running."

# All SQL files present?
foreach ($f in $WORLD_SQL) {
    if (-not (Test-Path $f)) {
        Write-Host "FAIL: SQL file missing: $f" -ForegroundColor Red
        exit 1
    }
}
Write-Host "OK: All $($WORLD_SQL.Count) SQL files present."

# ID collision check: entries 300001-345833 must be absent on live
$live300k = Invoke-LiveQuery "SELECT COUNT(*) FROM item_template WHERE entry BETWEEN 300001 AND 345833"
if ([int]$live300k -gt 0) {
    Write-Host "WARN: $live300k rows already exist in item_template 300001-345833 on live." -ForegroundColor Yellow
    Write-Host "      SQL files use DELETE before INSERT so re-apply is safe (idempotent)." -ForegroundColor Yellow
    Write-Host "      If this was an unexpected partial apply, investigate before continuing." -ForegroundColor Yellow
} else {
    Write-Host "OK: item_template 300001-345833 is clean on live (0 rows)."
}

# Kit entries 200000-200020 must be absent on live
$live200k = Invoke-LiveQuery "SELECT COUNT(*) FROM item_template WHERE entry BETWEEN 200000 AND 200020"
if ([int]$live200k -gt 0) {
    Write-Host "WARN: $live200k kit rows already exist in item_template 200000-200020 on live." -ForegroundColor Yellow
    Write-Host "      kits.sql uses DELETE before INSERT — re-apply is safe." -ForegroundColor Yellow
} else {
    Write-Host "OK: item_template 200000-200020 is clean on live (0 rows)."
}

# IEC 100008 must be absent
$liveIec = Invoke-LiveQuery "SELECT COUNT(*) FROM itemextendedcost_dbc WHERE ID = 100008"
if ([int]$liveIec -gt 0) {
    Write-Host "WARN: IEC 100008 already exists on live. kit_vendor.sql uses DELETE + INSERT — safe to re-apply." -ForegroundColor Yellow
} else {
    Write-Host "OK: itemextendedcost_dbc 100008 absent on live."
}

# Verify token 100017 exists (required by kit_vendor.sql's IEC definition)
$tokenExists = Invoke-LiveQuery "SELECT COUNT(*) FROM item_template WHERE entry = 100017"
if ([int]$tokenExists -eq 0) {
    Write-Host "FAIL: item_template 100017 (Nemesis token) is missing on live!" -ForegroundColor Red
    Write-Host "      The kit vendor IEC 100008 references this item. Deploy Nemesis system first." -ForegroundColor Red
    exit 1
}
Write-Host "OK: item_template 100017 (Nemesis token) present on live."

# Check Nemesis vendor entries exist (pre-existing — must not be absent)
$v101 = Invoke-LiveQuery "SELECT COUNT(*) FROM npc_vendor WHERE entry = 190101"
$v102 = Invoke-LiveQuery "SELECT COUNT(*) FROM npc_vendor WHERE entry = 190102"
$v103 = Invoke-LiveQuery "SELECT COUNT(*) FROM npc_vendor WHERE entry = 190103"
if ([int]$v101 -eq 0 -or [int]$v102 -eq 0 -or [int]$v103 -eq 0) {
    Write-Host "WARN: One or more Nemesis vendor entries (190101/190102/190103) have 0 rows on live." -ForegroundColor Yellow
    Write-Host "      Kit rows will still be inserted (kit_vendor.sql does not depend on pre-existing rows)." -ForegroundColor Yellow
    Write-Host "      Values: 190101=$v101 rows, 190102=$v102 rows, 190103=$v103 rows" -ForegroundColor Yellow
} else {
    Write-Host "OK: Nemesis vendors 190101($v101 rows) / 190102($v102 rows) / 190103($v103 rows) exist."
}

# No snapshot yet? (first-time apply guard)
if (Test-Path $SNAPSHOT_FILE) {
    Write-Host "WARN: Snapshot file already exists at:" -ForegroundColor Yellow
    Write-Host "      $SNAPSHOT_FILE" -ForegroundColor Yellow
    Write-Host "      This means apply.ps1 was previously run. The snapshot will NOT be overwritten." -ForegroundColor Yellow
    Write-Host "      If you want a fresh snapshot, delete the existing file first." -ForegroundColor Yellow
    $SKIP_SNAPSHOT = $true
} else {
    $SKIP_SNAPSHOT = $false
    Write-Host "OK: No prior snapshot found — will create fresh snapshot in Step 2."
}

Write-Host ""
Write-Host "Pre-flight checks passed." -ForegroundColor Green

# ============================================================
# STEP 2: Snapshot acore_world
# ============================================================
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host " STEP 2: Snapshot acore_world" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan

if ($SKIP_SNAPSHOT) {
    Write-Host "Skipped: snapshot already exists at $SNAPSHOT_FILE" -ForegroundColor Yellow
    Write-Host "         Using existing snapshot as rollback base."
} else {
    Write-Host "  Destination: $SNAPSHOT_FILE"
    Write-Host "  This is a full mysqldump of acore_world. It may take 2-5 minutes."
    Write-Host "  The rollback.ps1 will restore from this file if needed."

    if (Confirm-Step "Take full snapshot of $WORLD_DB now?") {
        Write-Host "  Dumping $WORLD_DB ..." -ForegroundColor Yellow
        # Run mysqldump inside container, stream out and compress on host
        $dumpCmd = "docker exec $DB_CONTAINER mysqldump -u $DB_USER -p$DB_PASS --default-character-set=utf8mb4 --single-transaction --routines --triggers $WORLD_DB"
        $proc = Start-Process -FilePath "cmd.exe" -ArgumentList "/c $dumpCmd | gzip > `"$SNAPSHOT_FILE`"" -Wait -PassThru -NoNewWindow
        if ($proc.ExitCode -ne 0 -or -not (Test-Path $SNAPSHOT_FILE)) {
            Write-Host "FAIL: mysqldump failed or snapshot file not created." -ForegroundColor Red
            Write-Host "      Do NOT proceed without a valid snapshot — rollback will be impossible." -ForegroundColor Red
            exit 1
        }
        $snapSize = (Get-Item $SNAPSHOT_FILE).Length / 1MB
        Write-Host ("OK: Snapshot created. Size: {0:F1} MB" -f $snapSize) -ForegroundColor Green
        Write-Host "    Path: $SNAPSHOT_FILE"
    } else {
        Write-Host "ABORT: Snapshot skipped by user. Cannot proceed safely without a snapshot." -ForegroundColor Red
        Write-Host "       Re-run apply.ps1 and confirm the snapshot step, or ensure a recent backup exists." -ForegroundColor Red
        exit 1
    }
}

# ============================================================
# STEP 3: CREATE item_upgrade_chain table if absent
# ============================================================
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host " STEP 3: Create item_upgrade_chain table" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan

$tableExists = Invoke-LiveQuery "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='$WORLD_DB' AND table_name='item_upgrade_chain'"

if ([int]$tableExists -gt 0) {
    Write-Host "OK: item_upgrade_chain already exists on live — skipping CREATE." -ForegroundColor Green
} else {
    Write-Host "  item_upgrade_chain is absent on live. Creating now ..."
    if (Confirm-Step "CREATE TABLE item_upgrade_chain in $WORLD_DB?") {
        docker exec $DB_CONTAINER mysql -u $DB_USER -p$DB_PASS --default-character-set=utf8mb4 $WORLD_DB 2>$null -e $CHAIN_DDL
        if ($LASTEXITCODE -ne 0) {
            Write-Host "FAIL: CREATE TABLE item_upgrade_chain failed." -ForegroundColor Red
            exit 1
        }
        $verifyTable = Invoke-LiveQuery "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='$WORLD_DB' AND table_name='item_upgrade_chain'"
        if ([int]$verifyTable -eq 0) {
            Write-Host "FAIL: Table creation could not be verified." -ForegroundColor Red
            exit 1
        }
        Write-Host "OK: item_upgrade_chain created." -ForegroundColor Green
    } else {
        Write-Host "ABORT: Table creation skipped — gear_ascension_proto.sql will fail without it." -ForegroundColor Red
        exit 1
    }
}

# ============================================================
# STEP 4: Apply SQL files to acore_world
# ============================================================
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host " STEP 4: Apply SQL files to acore_world" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Files (in dependency order):"
$labels = @(
    "legacy cleanup — 0 rows on live, no-op",
    "21 kit item_template + spell_dbc 105000",
    "spell 105000 polish + spell_script_names",
    "8,480 green/blue tier copies + locale + chain (181k lines — takes ~2-4 min)",
    "white tier copies + locale + chain (64k lines — takes ~1 min)",
    "IEC 100008 + 21 npc_vendor kit rows"
)
for ($i = 0; $i -lt $WORLD_SQL.Count; $i++) {
    Write-Host "    $($i+1). $(Split-Path $WORLD_SQL[$i] -Leaf)  --  $($labels[$i])"
}

if (Confirm-Step "Apply all $($WORLD_SQL.Count) files to $WORLD_DB?") {
    for ($i = 0; $i -lt $WORLD_SQL.Count; $i++) {
        Apply-SqlFile -FilePath $WORLD_SQL[$i] -Label $labels[$i]
    }
    Write-Host ""
    Write-Host "All SQL files applied." -ForegroundColor Green
}

# ============================================================
# STEP 5: Post-apply verification
# ============================================================
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host " STEP 5: Post-apply verification" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan

$r1 = Invoke-LiveQuery "SELECT COUNT(*) FROM item_template WHERE entry BETWEEN 300001 AND 345833"
Write-Host "  item_template 300001-345833:            $r1 rows   (expected: 8480)"
if ([int]$r1 -ne 8480) { Write-Host "  !! MISMATCH" -ForegroundColor Red }

$r2 = Invoke-LiveQuery "SELECT COUNT(*) FROM item_template WHERE entry BETWEEN 200000 AND 200020"
Write-Host "  item_template 200000-200020 (kits):     $r2 rows   (expected: 21)"
if ([int]$r2 -ne 21) { Write-Host "  !! MISMATCH" -ForegroundColor Red }

$r3 = Invoke-LiveQuery "SELECT COUNT(*) FROM item_template_locale WHERE ID BETWEEN 300001 AND 345833 AND locale='ruRU'"
Write-Host "  item_template_locale 300001-345833 ruRU: $r3 rows  (expected: 8472)"
if ([int]$r3 -lt 8470) { Write-Host "  !! LOW COUNT" -ForegroundColor Red }

$r4 = Invoke-LiveQuery "SELECT COUNT(*) FROM item_upgrade_chain"
Write-Host "  item_upgrade_chain total rows:           $r4        (expected: 8480)"
if ([int]$r4 -ne 8480) { Write-Host "  !! MISMATCH" -ForegroundColor Red }

$r5 = Invoke-LiveQuery "SELECT COUNT(*) FROM npc_vendor WHERE entry IN (190101,190102,190103) AND item BETWEEN 200000 AND 200020"
Write-Host "  npc_vendor kit rows:                     $r5        (expected: 21)"
if ([int]$r5 -ne 21) { Write-Host "  !! MISMATCH" -ForegroundColor Red }

$r6 = Invoke-LiveQuery "SELECT COUNT(*) FROM itemextendedcost_dbc WHERE ID = 100008"
Write-Host "  itemextendedcost_dbc 100008:             $r6        (expected: 1)"
if ([int]$r6 -ne 1) { Write-Host "  !! MISMATCH" -ForegroundColor Red }

$r7 = Invoke-LiveQuery "SELECT CastingTimeIndex, Effect_1 FROM spell_dbc WHERE ID = 105000"
Write-Host "  spell_dbc 105000 (CastingTimeIndex,Effect_1): $r7   (expected: 5	77)"

$r8 = Invoke-LiveQuery "SELECT ScriptName FROM spell_script_names WHERE spell_id = 105000"
Write-Host "  spell_script_names 105000:               $r8        (expected: spell_gear_ascension_apply_kit)"

Write-Host ""
Write-Host "Verification complete. Review any MISMATCH lines above." -ForegroundColor Cyan
Write-Host "If all look good, proceed to Step 6 (image build)." -ForegroundColor Cyan

# ============================================================
# STEP 6: Build live worldserver image
# ============================================================
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host " STEP 6: Build live worldserver image" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  mod-gear-ascension C++ module must be compiled into the image."
Write-Host "  Branch: feat/wow-ak-1-gear-ascension"
Write-Host ""
Write-Host "  RECOMMENDATION: Stop ac-worldserver-ptr first to free WSL2 RAM:"
Write-Host "    docker stop ac-worldserver-ptr"
Write-Host ""
Write-Host "  Build command (run from repo root):"
Write-Host "    docker compose build ac-worldserver"
Write-Host ""

if (Confirm-Step "Run docker compose build ac-worldserver now?") {
    Set-Location $REPO_ROOT
    Write-Host "Building (this will take several minutes) ..." -ForegroundColor Yellow
    docker compose build ac-worldserver
    if ($LASTEXITCODE -ne 0) {
        Write-Host "FAIL: docker compose build ac-worldserver failed (exit $LASTEXITCODE)" -ForegroundColor Red
        Write-Host "      DB apply is complete and safe. Fix the build issue before restarting the server." -ForegroundColor Red
        exit 1
    }
    Write-Host "OK: Image rebuilt with mod-gear-ascension." -ForegroundColor Green
} else {
    Write-Host "Skipped image build. DB apply is complete." -ForegroundColor Yellow
    Write-Host "Run the build separately before restarting the worldserver." -ForegroundColor Yellow
}

# ============================================================
# STEP 7: Worldserver restart (DEFERRED)
# ============================================================
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host " STEP 7: Worldserver restart — DEFERRED" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Per owner decision, the live worldserver restart is DEFERRED."
Write-Host "  Gear Ascension is NOT active until ac-worldserver-v2 restarts with the new image."
Write-Host ""
Write-Host "  When ready to activate, run:"
Write-Host "    docker compose up -d ac-worldserver   (from $REPO_ROOT)"
Write-Host ""
Write-Host "  BEFORE restarting, also complete these manual steps:"
Write-Host "  [A] Edit env\dist\etc\modules\mod_ahbot.conf:"
Write-Host "        AuctionHouseBot.ListedItemIDRestrict.Enabled = 1"
Write-Host "        AuctionHouseBot.MaxItemID = 199999"
Write-Host "  [B] Distribute client MPQ patch to players (Item.dbc + ItemExtendedCost.dbc + Spell.dbc)"

# ============================================================
# Done
# ============================================================
Write-Host ""
Write-Host "========================================" -ForegroundColor Green
Write-Host " Apply complete." -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
Write-Host "  DB footprint is live in acore_world."
Write-Host "  Snapshot (rollback base): $SNAPSHOT_FILE"
Write-Host ""
Write-Host "  Remaining manual steps before player-visible activation:"
Write-Host "    1. Edit mod_ahbot.conf (MaxItemID=199999)"
Write-Host "    2. Distribute client MPQ"
Write-Host "    3. docker compose up -d ac-worldserver (when ready)"
Write-Host ""
Write-Host "  If smoke tests fail after restart, run:"
Write-Host "    pwsh `"$PKG_DIR\rollback.ps1`""
Write-Host ""
Write-Host "  Report success to the agent so deployments.log can be updated."
