-- mod-environmental-effects v2 — spell_dbc (server effects)
-- 147 zone buffs (107000+) + 29 shared debuffs (107500+) + 1 night (108500).
-- SpellIconID=1 placeholder; client names/icons come via MPQ later.
-- Generated by scripts/gen_spells.py — do not hand-edit.

DELETE FROM `spell_dbc` WHERE `ID` BETWEEN 107000 AND 107199;
DELETE FROM `spell_dbc` WHERE `ID` BETWEEN 107500 AND 107599;
DELETE FROM `spell_dbc` WHERE `ID` = 108500;

-- buffs (147)
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107000, 2147483648, 1, 21, 101, 1, -1, 6, 79, 9, 1, 16, 1, 1, 1, 'Холодный ветер', 'Холодный ветер', '+10% урона холодом', '+10% урона холодом'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107001, 2147483648, 1, 21, 101, 1, -1, 6, 137, 1, 1, -1, 1, 1, 1, 'Эхо Альтерака', 'Эхо Альтерака', '+2% ко всем хар-кам', '+2% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107002, 2147483648, 1, 21, 101, 1, -1, 6, 22, 9, 1, 4, 1, 1, 1, 'Горный туман', 'Горный туман', 'защита от огня +10', 'защита от огня +10'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107003, 2147483648, 1, 21, 101, 1, -1, 6, 79, 9, 1, 4, 1, 1, 1, 'Остаточный Дух Рагнароса', 'Остаточный Дух Рагнароса', '+10% урона огнём', '+10% урона огнём'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107004, 2147483648, 1, 21, 101, 1, -1, 6, 31, 2, 1, 0, 1, 1, 1, 'Попутный суховей', 'Попутный суховей', '+3% скорости перемещения', '+3% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107005, 2147483648, 1, 21, 101, 1, -1, 6, 137, 1, 1, -1, 1, 1, 1, 'Тень каньона', 'Тень каньона', '+2% ко всем хар-кам', '+2% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107006, 2147483648, 1, 21, 101, 1, -1, 6, 79, 9, 1, 8, 1, 1, 1, 'Обволакивающая влажность', 'Обволакивающая влажность', '+10% урона природой', '+10% урона природой'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107007, 2147483648, 1, 21, 101, 1, -1, 6, 137, 2, 1, -1, 1, 1, 1, 'Освежающий болотный бриз', 'Освежающий болотный бриз', '+3% ко всем хар-кам', '+3% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107008, 2147483648, 1, 21, 101, 1, -1, 6, 22, 9, 1, 4, 1, 1, 1, 'Влажный ветер', 'Влажный ветер', 'защита от огня +10', 'защита от огня +10'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107009, 2147483648, 1, 21, 101, 1, -1, 6, 79, 9, 1, 126, 1, 1, 1, 'Древняя сила вуду', 'Древняя сила вуду', '+10% к силе заклинаний', '+10% к силе заклинаний'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107010, 2147483648, 1, 21, 101, 1, -1, 6, 137, 2, 1, -1, 1, 1, 1, 'Освежающий бриз', 'Освежающий бриз', '+3% ко всем хар-кам', '+3% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107011, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Свежий ветер', 'Свежий ветер', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107012, 2147483648, 1, 21, 101, 1, -1, 6, 22, 9, 1, 16, 1, 1, 1, 'Жар пустыни', 'Жар пустыни', 'защита от холода +10', 'защита от холода +10'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107013, 2147483648, 1, 21, 101, 1, -1, 6, 31, 0, 1, 0, 1, 1, 1, 'Слабый ветер', 'Слабый ветер', '+1% скорости перемещения', '+1% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107014, 2147483648, 1, 21, 101, 1, -1, 6, 137, 1, 1, 2, 1, 1, 1, 'Тень от каньона', 'Тень от каньона', '+2% выносливости', '+2% выносливости'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107015, 2147483648, 1, 21, 101, 1, -1, 6, 137, 4, 1, 2, 1, 1, 1, 'Солнечная погода', 'Солнечная погода', '+5% выносливости', '+5% выносливости'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107016, 2147483648, 1, 21, 101, 1, -1, 6, 137, 2, 1, -1, 1, 1, 1, 'Эхо Стальгорна', 'Эхо Стальгорна', '+3% ко всем хар-кам', '+3% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107017, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Свежий ветер', 'Свежий ветер', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107018, 2147483648, 1, 21, 101, 1, -1, 6, 79, 9, 1, 32, 1, 1, 1, 'Слабое присутствие порчи', 'Слабое присутствие порчи', '+10% урона тенью', '+10% урона тенью'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107019, 2147483648, 1, 21, 101, 1, -1, 6, 137, 2, 1, -1, 1, 1, 1, 'Грибные споры', 'Грибные споры', '+3% ко всем хар-кам', '+3% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107020, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Свежий ветер', 'Свежий ветер', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107021, 2147483648, 1, 21, 101, 1, -1, 6, 79, 9, 1, 32, 1, 1, 1, 'Сильное присутствие порчи', 'Сильное присутствие порчи', '+10% урона тенью', '+10% урона тенью'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107022, 2147483648, 1, 21, 101, 1, -1, 6, 137, 4, 1, -1, 1, 1, 1, 'Больше грибные споры', 'Больше грибные споры', '+5% ко всем хар-кам', '+5% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107023, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Эхо Серебряного Авангарда', 'Эхо Серебряного Авангарда', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107024, 2147483648, 1, 21, 101, 1, -1, 6, 137, 4, 1, 2, 1, 1, 1, 'Солнечная погода', 'Солнечная погода', '+5% выносливости', '+5% выносливости'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107025, 2147483648, 1, 21, 101, 1, -1, 6, 137, 2, 1, -1, 1, 1, 1, 'Эхо Приозерье', 'Эхо Приозерье', '+3% ко всем хар-кам', '+3% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107026, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Свежий ветер', 'Свежий ветер', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107027, 2147483648, 1, 21, 101, 1, -1, 6, 137, 4, 1, 2, 1, 1, 1, 'Солнечная погода', 'Солнечная погода', '+5% выносливости', '+5% выносливости'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107028, 2147483648, 1, 21, 101, 1, -1, 6, 137, 0, 1, -1, 1, 1, 1, 'Слабое эхо Стальгорна', 'Слабое эхо Стальгорна', '+1% ко всем хар-кам', '+1% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107029, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Свежий ветер', 'Свежий ветер', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107030, 2147483648, 1, 21, 101, 1, -1, 6, 137, 4, 1, 2, 1, 1, 1, 'Солнечная погода', 'Солнечная погода', '+5% выносливости', '+5% выносливости'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107031, 2147483648, 1, 21, 101, 1, -1, 6, 137, 1, 1, -1, 1, 1, 1, 'Прохладный ветер', 'Прохладный ветер', '+2% ко всем хар-кам', '+2% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107032, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Свежий ветер', 'Свежий ветер', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107033, 2147483648, 1, 21, 101, 1, -1, 6, 79, 9, 1, 126, 1, 1, 1, 'Аура Медива', 'Аура Медива', '+10% магического урона', '+10% магического урона'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107034, 2147483648, 1, 21, 101, 1, -1, 6, 137, 1, 1, -1, 1, 1, 1, 'Прохладный ветер', 'Прохладный ветер', '+2% ко всем хар-кам', '+2% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107035, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Свежий ветер', 'Свежий ветер', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107036, 2147483648, 1, 21, 101, 1, -1, 6, 22, 9, 1, 4, 1, 1, 1, 'Горная свежесть', 'Горная свежесть', '+10 к защите от огня', '+10 к защите от огня'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107037, 2147483648, 1, 21, 101, 1, -1, 6, 137, 1, 1, -1, 1, 1, 1, 'Прохладный ветер', 'Прохладный ветер', '+2% ко всем хар-кам', '+2% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107038, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Свежий ветер', 'Свежий ветер', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107039, 2147483648, 1, 21, 101, 1, -1, 6, 137, 4, 1, -1, 1, 1, 1, 'Эхо Чёрной горы', 'Эхо Чёрной горы', '+5% ко всем хар-кам', '+5% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107040, 2147483648, 1, 21, 101, 1, -1, 6, 22, 9, 1, 16, 1, 1, 1, 'Вулканический ветер', 'Вулканический ветер', '+10 к защите от мороза', '+10 к защите от мороза'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107041, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Свежий ветер', 'Свежий ветер', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107042, 2147483648, 1, 21, 101, 1, -1, 6, 137, 1, 1, -1, 1, 1, 1, 'Слабое эхо Штормграда', 'Слабое эхо Штормграда', '+2% ко всем хар-кам', '+2% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107043, 2147483648, 1, 21, 101, 1, -1, 6, 79, 4, 1, 32, 1, 1, 1, 'Присутствие нежити', 'Присутствие нежити', '+5% урона тьмой', '+5% урона тьмой'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107044, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Свежий ветер', 'Свежий ветер', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107045, 2147483648, 1, 21, 101, 1, -1, 6, 137, 4, 1, 2, 1, 1, 1, 'Древняя сила вуду', 'Древняя сила вуду', '+5% к выносливости', '+5% к выносливости'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107046, 2147483648, 1, 21, 101, 1, -1, 6, 137, 1, 1, -1, 1, 1, 1, 'Прохладный ветер', 'Прохладный ветер', '+2% ко всем хар-кам', '+2% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107047, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Свежий ветер', 'Свежий ветер', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107048, 2147483648, 1, 21, 101, 1, -1, 6, 137, 9, 1, -1, 1, 1, 1, 'Эхо Подгорода', 'Эхо Подгорода', '+10% ко всем хар-кам', '+10% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107049, 2147483648, 1, 21, 101, 1, -1, 6, 79, 1, 1, 32, 1, 1, 1, 'Слабое присутствие нежити', 'Слабое присутствие нежити', '+2% урона тьмой', '+2% урона тьмой'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107050, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Некротические газы', 'Некротические газы', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107051, 2147483648, 1, 21, 101, 1, -1, 6, 137, 1, 1, -1, 1, 1, 1, 'Слабое эхо Чёрной горы', 'Слабое эхо Чёрной горы', '+2% ко всем хар-кам', '+2% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107052, 2147483648, 1, 21, 101, 1, -1, 6, 22, 9, 1, 16, 1, 1, 1, 'Вулканический ветер', 'Вулканический ветер', '+10 к защите от мороза', '+10 к защите от мороза'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107053, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Свежий ветер', 'Свежий ветер', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107054, 2147483648, 1, 21, 101, 1, -1, 6, 137, 9, 1, -1, 1, 1, 1, 'Эхо Штормграда', 'Эхо Штормграда', '+10% ко всем хар-кам', '+10% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107055, 2147483648, 1, 21, 101, 1, -1, 6, 137, 4, 1, 2, 1, 1, 1, 'Солнечная погода', 'Солнечная погода', '+5% выносливости', '+5% выносливости'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107056, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Свежий ветер', 'Свежий ветер', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107057, 2147483648, 1, 21, 101, 1, -1, 6, 79, 9, 1, 64, 1, 1, 1, 'Эхо Высокорождённых', 'Эхо Высокорождённых', '+10% урона тайной магией', '+10% урона тайной магией'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107058, 2147483648, 1, 21, 101, 1, -1, 6, 137, 1, 1, -1, 1, 1, 1, 'Морской бриз', 'Морской бриз', '+2% ко всем хар-кам', '+2% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107059, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Свежий ветер', 'Свежий ветер', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107060, 2147483648, 1, 21, 101, 1, -1, 6, 133, 9, 1, 0, 1, 1, 1, 'Объятия вечной зимы', 'Объятия вечной зимы', '+10% урона морозом', '+10% урона морозом'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107061, 2147483648, 1, 21, 101, 1, -1, 6, 137, 2, 1, -1, 1, 1, 1, 'Эхо Хиджала', 'Эхо Хиджала', '+3% ко всем хар-кам', '+3% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107062, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Свежий ветер', 'Свежий ветер', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107063, 2147483648, 1, 21, 101, 1, -1, 6, 133, 2, 1, 0, 1, 1, 1, 'Первородная мощь', 'Первородная мощь', '+3% к ОЗ', '+3% к ОЗ'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107064, 2147483648, 1, 21, 101, 1, -1, 6, 137, 2, 1, -1, 1, 1, 1, 'Дыхание первозданной жизни', 'Дыхание первозданной жизни', '+3% ко всем хар-кам', '+3% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107065, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Свежий ветер', 'Свежий ветер', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `Effect_2`, `EffectAura_2`, `EffectBasePoints_2`, `EffectDieSides_2`, `EffectMiscValue_2`, `ImplicitTargetA_2`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107066, 2147483648, 1, 21, 101, 1, -1, 6, 88, 9, 1, 0, 1, 6, 110, 9, 1, 0, 1, 1, 1, 'Лесное благословение', 'Лесное благословение', 'реген вне боя +10%', 'реген вне боя +10%'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107067, 2147483648, 1, 21, 101, 1, -1, 6, 137, 2, 1, -1, 1, 1, 1, 'Покой Лунной поляны', 'Покой Лунной поляны', '+3% ко всем хар-кам', '+3% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107068, 2147483648, 1, 21, 101, 1, -1, 6, 79, 9, 1, 64, 1, 1, 1, 'Благодать Элуны', 'Благодать Элуны', '+10% урона тайной магией', '+10% урона тайной магией'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107069, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Вольные ветра', 'Вольные ветра', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107070, 2147483648, 1, 21, 101, 1, -1, 6, 137, 2, 1, -1, 1, 1, 1, 'Эхо Громового Утёса', 'Эхо Громового Утёса', '+3% ко всем хар-кам', '+3% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107071, 2147483648, 1, 21, 101, 1, -1, 6, 137, 4, 1, 2, 1, 1, 1, 'Солнечная погода', 'Солнечная погода', '+5% выносливости', '+5% выносливости'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107072, 2147483648, 1, 21, 101, 1, -1, 6, 79, 4, 1, 32, 1, 1, 1, 'Скверная порча', 'Скверная порча', '+5% урона тенью', '+5% урона тенью'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107073, 2147483648, 1, 21, 101, 1, -1, 6, 137, 2, 1, -1, 1, 1, 1, 'Гнилостные споры', 'Гнилостные споры', '+3% ко всем хар-кам', '+3% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107074, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Свежий ветер', 'Свежий ветер', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107075, 2147483648, 1, 21, 101, 1, -1, 6, 137, 1, 1, -1, 1, 1, 1, 'Безмолвие пустоши', 'Безмолвие пустоши', '+2% ко всем хар-кам', '+2% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107076, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Сухой ветер', 'Сухой ветер', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107077, 2147483648, 1, 21, 101, 1, -1, 6, 137, 4, 1, 2, 1, 1, 1, 'Солнечная погода', 'Солнечная погода', '+5% выносливости', '+5% выносливости'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107078, 2147483648, 1, 21, 101, 1, -1, 6, 132, 2, 1, 0, 1, 1, 1, 'Приятная слякоть', 'Приятная слякоть', '+3% к максимуму маны', '+3% к максимуму маны'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107079, 2147483648, 1, 21, 101, 1, -1, 6, 137, 2, 1, -1, 1, 1, 1, 'Болотный бриз', 'Болотный бриз', '+3% ко всем хар-кам', '+3% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107080, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Свежий ветер', 'Свежий ветер', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107081, 2147483648, 1, 21, 101, 1, -1, 6, 79, 9, 1, 64, 1, 1, 1, 'Присутствие древнего бога', 'Присутствие древнего бога', '+10% урона тайной магией', '+10% урона тайной магией'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107082, 2147483648, 1, 21, 101, 1, -1, 6, 31, 2, 1, 0, 1, 1, 1, 'Песчаный вихрь', 'Песчаный вихрь', '+3% скорости перемещения', '+3% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107083, 2147483648, 1, 21, 101, 1, -1, 6, 137, 1, 1, -1, 1, 1, 1, 'Тень дюн', 'Тень дюн', '+2% ко всем хар-кам', '+2% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107084, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Вольные ветра', 'Вольные ветра', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107085, 2147483648, 1, 21, 101, 1, -1, 6, 137, 2, 1, -1, 1, 1, 1, 'Эхо Перекрёстка', 'Эхо Перекрёстка', '+3% ко всем хар-кам', '+3% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107086, 2147483648, 1, 21, 101, 1, -1, 6, 137, 4, 1, 2, 1, 1, 1, 'Солнечная погода', 'Солнечная погода', '+5% выносливости', '+5% выносливости'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107087, 2147483648, 1, 21, 101, 1, -1, 6, 79, 9, 1, 4, 1, 1, 1, 'Жар недр', 'Жар недр', '+10% урона огнём', '+10% урона огнём'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107088, 2147483648, 1, 21, 101, 1, -1, 6, 31, 2, 1, 0, 1, 1, 1, 'Попутный суховей', 'Попутный суховей', '+3% скорости перемещения', '+3% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107089, 2147483648, 1, 21, 101, 1, -1, 6, 137, 1, 1, -1, 1, 1, 1, 'Тень бархана', 'Тень бархана', '+2% ко всем хар-кам', '+2% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `Effect_2`, `EffectAura_2`, `EffectBasePoints_2`, `EffectDieSides_2`, `EffectMiscValue_2`, `ImplicitTargetA_2`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107090, 2147483648, 1, 21, 101, 1, -1, 6, 88, 9, 1, 0, 1, 6, 110, 9, 1, 0, 1, 1, 1, 'Лесное благословение', 'Лесное благословение', 'реген вне боя +10%', 'реген вне боя +10%'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107091, 2147483648, 1, 21, 101, 1, -1, 6, 137, 2, 1, -1, 1, 1, 1, 'Эхо Дарнаса', 'Эхо Дарнаса', '+3% ко всем хар-кам', '+3% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107092, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Свежий ветер', 'Свежий ветер', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107093, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Вольные ветра', 'Вольные ветра', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107094, 2147483648, 1, 21, 101, 1, -1, 6, 137, 2, 1, -1, 1, 1, 1, 'Морской бриз', 'Морской бриз', '+3% ко всем хар-кам', '+3% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107095, 2147483648, 1, 21, 101, 1, -1, 6, 137, 4, 1, 2, 1, 1, 1, 'Солнечная погода', 'Солнечная погода', '+5% выносливости', '+5% выносливости'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107096, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Вольные ветра', 'Вольные ветра', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107097, 2147483648, 1, 21, 101, 1, -1, 6, 137, 1, 1, -1, 1, 1, 1, 'Эхо каньонов', 'Эхо каньонов', '+2% ко всем хар-кам', '+2% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107098, 2147483648, 1, 21, 101, 1, -1, 6, 137, 4, 1, 2, 1, 1, 1, 'Солнечная погода', 'Солнечная погода', '+5% выносливости', '+5% выносливости'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107099, 2147483648, 1, 21, 101, 1, -1, 6, 79, 9, 1, 8, 1, 1, 1, 'Дыхание грозы', 'Дыхание грозы', '+10% урона природой', '+10% урона природой'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107100, 2147483648, 1, 21, 101, 1, -1, 6, 137, 2, 1, -1, 1, 1, 1, 'Сочная зелень', 'Сочная зелень', '+3% ко всем хар-кам', '+3% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107101, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Свежий ветер', 'Свежий ветер', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107102, 2147483648, 1, 21, 101, 1, -1, 6, 79, 4, 1, 32, 1, 1, 1, 'Скверная порча', 'Скверная порча', '+5% урона тенью', '+5% урона тенью'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107103, 2147483648, 1, 21, 101, 1, -1, 6, 137, 2, 1, -1, 1, 1, 1, 'Эхо Чёрного храма', 'Эхо Чёрного храма', '+3% ко всем хар-кам', '+3% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107104, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Свежий ветер', 'Свежий ветер', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `Effect_2`, `EffectAura_2`, `EffectBasePoints_2`, `EffectDieSides_2`, `EffectMiscValue_2`, `ImplicitTargetA_2`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107105, 2147483648, 1, 21, 101, 1, -1, 6, 88, 9, 1, 0, 1, 6, 110, 9, 1, 0, 1, 1, 1, 'Лесное благословение', 'Лесное благословение', 'реген вне боя +10%', 'реген вне боя +10%'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107106, 2147483648, 1, 21, 101, 1, -1, 6, 137, 2, 1, -1, 1, 1, 1, 'Споровый бриз', 'Споровый бриз', '+3% ко всем хар-кам', '+3% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107107, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Свежий ветер', 'Свежий ветер', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107108, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Вольные ветра', 'Вольные ветра', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107109, 2147483648, 1, 21, 101, 1, -1, 6, 137, 2, 1, -1, 1, 1, 1, 'Дыхание Награнда', 'Дыхание Награнда', '+3% ко всем хар-кам', '+3% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107110, 2147483648, 1, 21, 101, 1, -1, 6, 137, 4, 1, 2, 1, 1, 1, 'Солнечная погода', 'Солнечная погода', '+5% выносливости', '+5% выносливости'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107111, 2147483648, 1, 21, 101, 1, -1, 6, 79, 9, 1, 64, 1, 1, 1, 'Эхо Солнечного Колодца', 'Эхо Солнечного Колодца', '+10% урона тайной магией', '+10% урона тайной магией'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107112, 2147483648, 1, 21, 101, 1, -1, 6, 137, 2, 1, -1, 1, 1, 1, 'Морской бриз', 'Морской бриз', '+3% ко всем хар-кам', '+3% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107113, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Свежий ветер', 'Свежий ветер', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107114, 2147483648, 1, 21, 101, 1, -1, 6, 79, 9, 1, 4, 1, 1, 1, 'Жар недр', 'Жар недр', '+10% урона огнём', '+10% урона огнём'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107115, 2147483648, 1, 21, 101, 1, -1, 6, 137, 2, 1, -1, 1, 1, 1, 'Эхо Цитадели Адского Пламени', 'Эхо Цитадели Адского Пламени', '+3% ко всем хар-кам', '+3% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107116, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Свежий ветер', 'Свежий ветер', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107117, 2147483648, 1, 21, 101, 1, -1, 6, 79, 9, 1, 32, 1, 1, 1, 'Скверная порча', 'Скверная порча', '+10% урона тенью', '+10% урона тенью'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107118, 2147483648, 1, 21, 101, 1, -1, 6, 137, 2, 1, -1, 1, 1, 1, 'Эхо Затмения', 'Эхо Затмения', '+3% ко всем хар-кам', '+3% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107119, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Свежий ветер', 'Свежий ветер', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107120, 2147483648, 1, 21, 101, 1, -1, 6, 79, 9, 1, 64, 1, 1, 1, 'Эхо Высокорождённых', 'Эхо Высокорождённых', '+10% урона тайной магией', '+10% урона тайной магией'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107121, 2147483648, 1, 21, 101, 1, -1, 6, 137, 2, 1, -1, 1, 1, 1, 'Энергия Пустоты', 'Энергия Пустоты', '+3% ко всем хар-кам', '+3% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107122, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Свежий ветер', 'Свежий ветер', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107123, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Вольные ветра', 'Вольные ветра', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107124, 2147483648, 1, 21, 101, 1, -1, 6, 137, 2, 1, -1, 1, 1, 1, 'Северный бриз', 'Северный бриз', '+3% ко всем хар-кам', '+3% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107125, 2147483648, 1, 21, 101, 1, -1, 6, 137, 4, 1, 2, 1, 1, 1, 'Солнечная погода', 'Солнечная погода', '+5% выносливости', '+5% выносливости'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107126, 2147483648, 1, 21, 101, 1, -1, 6, 133, 9, 1, 0, 1, 1, 1, 'Объятия вечной зимы', 'Объятия вечной зимы', '+10% урона морозом', '+10% урона морозом'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107127, 2147483648, 1, 21, 101, 1, -1, 6, 137, 2, 1, -1, 1, 1, 1, 'Эхо Ульдуара', 'Эхо Ульдуара', '+3% ко всем хар-кам', '+3% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107128, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Свежий ветер', 'Свежий ветер', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107129, 2147483648, 1, 21, 101, 1, -1, 6, 133, 9, 1, 0, 1, 1, 1, 'Объятия вечной зимы', 'Объятия вечной зимы', '+10% урона морозом', '+10% урона морозом'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107130, 2147483648, 1, 21, 101, 1, -1, 6, 137, 2, 1, -1, 1, 1, 1, 'Благословение драконов', 'Благословение драконов', '+3% ко всем хар-кам', '+3% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107131, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Свежий ветер', 'Свежий ветер', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107132, 2147483648, 1, 21, 101, 1, -1, 6, 79, 9, 1, 32, 1, 1, 1, 'Скверная порча', 'Скверная порча', '+10% урона тенью', '+10% урона тенью'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107133, 2147483648, 1, 21, 101, 1, -1, 6, 137, 2, 1, -1, 1, 1, 1, 'Сила троллей-берсерков', 'Сила троллей-берсерков', '+3% ко всем хар-кам', '+3% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107134, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Свежий ветер', 'Свежий ветер', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107135, 2147483648, 1, 21, 101, 1, -1, 6, 133, 9, 1, 0, 1, 1, 1, 'Объятия вечной зимы', 'Объятия вечной зимы', '+10% урона морозом', '+10% урона морозом'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107136, 2147483648, 1, 21, 101, 1, -1, 6, 137, 2, 1, -1, 1, 1, 1, 'Эхо Серебряного Авангарда', 'Эхо Серебряного Авангарда', '+3% ко всем хар-кам', '+3% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107137, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Свежий ветер', 'Свежий ветер', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107138, 2147483648, 1, 21, 101, 1, -1, 6, 79, 9, 1, 64, 1, 1, 1, 'Эхо Высокорождённых', 'Эхо Высокорождённых', '+10% урона тайной магией', '+10% урона тайной магией'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107139, 2147483648, 1, 21, 101, 1, -1, 6, 137, 2, 1, -1, 1, 1, 1, 'Звенящие кристаллы', 'Звенящие кристаллы', '+3% ко всем хар-кам', '+3% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107140, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Свежий ветер', 'Свежий ветер', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107141, 2147483648, 1, 21, 101, 1, -1, 6, 133, 2, 1, 0, 1, 1, 1, 'Первородная мощь', 'Первородная мощь', '+3% к ОЗ', '+3% к ОЗ'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107142, 2147483648, 1, 21, 101, 1, -1, 6, 137, 2, 1, -1, 1, 1, 1, 'Дыхание Титанов', 'Дыхание Титанов', '+3% ко всем хар-кам', '+3% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107143, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Свежий ветер', 'Свежий ветер', '+5% скорости перемещения', '+5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107144, 2147483648, 1, 21, 101, 1, -1, 6, 137, 1, 1, -1, 1, 1, 1, 'Сила дикой чащи', 'Сила дикой чащи', '+2% ко всем хар-кам', '+2% ко всем хар-кам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107145, 2147483648, 1, 21, 101, 1, -1, 6, 137, 4, 1, 2, 1, 1, 1, 'Зов медведей', 'Зов медведей', '+5% выносливости', '+5% выносливости'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107146, 2147483648, 1, 21, 101, 1, -1, 6, 31, 4, 1, 0, 1, 1, 1, 'Свежий ветер', 'Свежий ветер', '+5% скорости перемещения', '+5% скорости перемещения'
);

-- debuffs (29)
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107500, 2214592512, 1, 21, 101, 1, -1, 6, 22, -11, 1, 8, 1, 1, 1, 'Дождь', 'Дождь', 'защита от природы -10', 'защита от природы -10'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107501, 2214592512, 1, 21, 101, 1, -1, 6, 137, -6, 1, -1, 1, 1, 1, 'Промозглый ветер', 'Промозглый ветер', '-5% ко всем характеристикам', '-5% ко всем характеристикам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107502, 2214592512, 1, 21, 101, 1, -1, 6, 33, -4, 1, 0, 1, 1, 1, 'Промозглый ливень', 'Промозглый ливень', '-3% скорости', '-3% скорости'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107503, 2214592512, 1, 21, 101, 1, -1, 6, 79, -6, 1, 64, 1, 1, 1, 'Сильная сырость', 'Сильная сырость', '-5% наносимого урона тайной магией', '-5% наносимого урона тайной магией'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107504, 2214592512, 1, 21, 101, 1, -1, 6, 87, 14, 1, 32, 1, 1, 1, 'Смрад из некроситета', 'Смрад из некроситета', '+15% получ. урона тенью', '+15% получ. урона тенью'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107505, 2214592512, 1, 21, 101, 1, -1, 6, 22, -11, 1, 8, 1, 1, 1, 'Тропическая морось', 'Тропическая морось', 'защита от природы -10', 'защита от природы -10'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107506, 2214592512, 1, 21, 101, 1, -1, 6, 137, -6, 1, -1, 1, 1, 1, 'Трупный запах', 'Трупный запах', '-5% ко всем характеристикам', '-5% ко всем характеристикам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107507, 2214592512, 1, 21, 101, 1, -1, 6, 87, 9, 1, 32, 1, 1, 1, 'Трупный смрад', 'Трупный смрад', '+10% получ. урона тенью', '+10% получ. урона тенью'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107508, 2214592512, 1, 21, 101, 1, -1, 6, 133, 4, 1, 0, 1, 1, 1, 'Лютая стужа', 'Лютая стужа', '+5% получ. урона морозом', '+5% получ. урона морозом'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107509, 2214592512, 1, 21, 101, 1, -1, 6, 33, -3, 1, 0, 1, 1, 1, 'Лёгкий снегопад', 'Лёгкий снегопад', '-2% скорости перемещения', '-2% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107510, 2214592512, 1, 21, 101, 1, -1, 6, 33, -6, 1, 0, 1, 1, 1, 'Сильный снегопад', 'Сильный снегопад', '-5% скорости перемещения', '-5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107511, 2214592512, 1, 21, 101, 1, -1, 6, 87, 9, 1, 4, 1, 1, 1, 'Иссушающий зной', 'Иссушающий зной', '+10% получ. урона огнём', '+10% получ. урона огнём'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107512, 2214592512, 1, 21, 101, 1, -1, 6, 137, -4, 1, -1, 1, 1, 1, 'Непроглядная взвесь', 'Непроглядная взвесь', '-3% ко всем характеристикам', '-3% ко всем характеристикам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107513, 2214592512, 1, 21, 101, 1, -1, 6, 33, -6, 1, 0, 1, 1, 1, 'Песчаная буря', 'Песчаная буря', '-5% скорости перемещения', '-5% скорости перемещения'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107514, 2214592512, 1, 21, 101, 1, -1, 6, 87, 4, 1, 4, 1, 1, 1, 'Сухой воздух', 'Сухой воздух', '+5% получ. урона огнём', '+5% получ. урона огнём'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107515, 2214592512, 1, 21, 101, 1, -1, 6, 87, 9, 1, 8, 1, 1, 1, 'Ядовитая взвесь', 'Ядовитая взвесь', '+10% получ. урона природой', '+10% получ. урона природой'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107516, 2214592512, 1, 21, 101, 1, -1, 6, 22, -21, 1, 4, 1, 1, 1, 'Адский пепел', 'Адский пепел', 'защита от огня -20', 'защита от огня -20'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107517, 2214592512, 1, 21, 101, 1, -1, 6, 87, 9, 1, 32, 1, 1, 1, 'Воля Плети', 'Воля Плети', '+10% получ. урона тенью', '+10% получ. урона тенью'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107518, 2214592512, 1, 21, 101, 1, -1, 6, 22, -11, 1, 64, 1, 1, 1, 'Дикая мана', 'Дикая мана', 'защита от тайной магии -10', 'защита от тайной магии -10'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107519, 2214592512, 1, 21, 101, 1, -1, 6, 22, -11, 1, 4, 1, 1, 1, 'Жар недр', 'Жар недр', '-10 защиты от огня', '-10 защиты от огня'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107520, 2214592512, 1, 21, 101, 1, -1, 6, 22, -21, 1, 64, 1, 1, 1, 'Нестабильная мана', 'Нестабильная мана', 'защита от тайной магии -20', 'защита от тайной магии -20'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107521, 2214592512, 1, 21, 101, 1, -1, 6, 22, -11, 1, 4, 1, 1, 1, 'Палящее солнце', 'Палящее солнце', 'защита от огня -10', 'защита от огня -10'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107522, 2214592512, 1, 21, 101, 1, -1, 6, 137, -4, 1, -1, 1, 1, 1, 'Пыльные столбы', 'Пыльные столбы', '-3% ко всем характеристикам', '-3% ко всем характеристикам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107523, 2214592512, 1, 21, 101, 1, -1, 6, 137, -6, 1, -1, 1, 1, 1, 'Скверный смог', 'Скверный смог', '-5% ко всем характеристикам', '-5% ко всем характеристикам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107524, 2214592512, 1, 21, 101, 1, -1, 6, 22, -6, 1, 4, 1, 1, 1, 'Слабый жар недр', 'Слабый жар недр', '-5 защиты от огня', '-5 защиты от огня'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107525, 2214592512, 1, 21, 101, 1, -1, 6, 87, 9, 1, 32, 1, 1, 1, 'Тлен Драконьего Погоста', 'Тлен Драконьего Погоста', '+10% получ. урона тенью', '+10% получ. урона тенью'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107526, 2214592512, 1, 21, 101, 1, -1, 6, 87, 9, 1, 32, 1, 1, 1, 'Чумной туман', 'Чумной туман', '+10% получ. урона тенью', '+10% получ. урона тенью'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107527, 2214592512, 1, 21, 101, 1, -1, 6, 137, -6, 1, -1, 1, 1, 1, 'Шквальные ветра', 'Шквальные ветра', '-5% ко всем характеристикам', '-5% ко всем характеристикам'
);
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    107528, 2214592512, 1, 21, 101, 1, -1, 6, 137, -11, 1, -1, 1, 1, 1, 'Эхо Тёмного портала', 'Эхо Тёмного портала', '-10% ко всем хар-кам', '-10% ко всем хар-кам'
);

-- night debuff
REPLACE INTO `spell_dbc` (
    `ID`, `Attributes`, `CastingTimeIndex`, `DurationIndex`, `ProcChance`, `RangeIndex`, `EquippedItemClass`, `Effect_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValue_1`, `ImplicitTargetA_1`, `SchoolMask`, `SpellIconID`, `Name_Lang_enUS`, `Name_Lang_ruRU`, `Description_Lang_enUS`, `Description_Lang_ruRU`
) VALUES (
    108500, 2214592512, 1, 21, 101, 1, -1, 6, 137, -4, 1, -1, 1, 1, 1, 'Покров ночи', 'Покров ночи', '-3% ко всем характеристикам', '-3% ко всем характеристикам'
);
