-- ============================================================================
-- Nemesis Familiar Gacha — family 8 (Демонический / demon)
-- AUTO-GENERATED by scripts/familiar-gen-sql.ps1 from 08_demon.json
-- Do not hand-edit: change the JSON and regenerate.
--
-- amount = EffectBasePoints + 1 (DieSides=1). buff=0x80000000,
-- debuff=0x84000000 (NO_AURA_CANCEL | AURA_IS_DEBUFF). See generator header.
-- ============================================================================

-- STEP 1: spell_dbc — summon spells
DELETE FROM spell_dbc WHERE ID IN (102070, 102071, 102072, 102073, 102074, 102075, 102076, 102077, 102078, 102079);
REPLACE INTO spell_dbc (ID, Attributes, CastingTimeIndex, DurationIndex, RangeIndex, EquippedItemClass, Effect_1, EffectMiscValue_1, EffectMiscValueB_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS) VALUES
(102070, 262416, 1, 21, 1, -1, 28, 191070, 41, 32, 1, 214, 'Summon Familiar: Ловец Скверны'),
(102071, 262416, 1, 21, 1, -1, 28, 191071, 41, 32, 1, 214, 'Summon Familiar: Испуганный Ловец Скверны'),
(102072, 262416, 1, 21, 1, -1, 28, 191072, 41, 32, 1, 3171, 'Summon Familiar: Грелль'),
(102073, 262416, 1, 21, 1, -1, 28, 191073, 41, 32, 1, 3171, 'Summon Familiar: Линялый Грелль'),
(102074, 262416, 1, 21, 1, -1, 28, 191074, 41, 32, 1, 135, 'Summon Familiar: Глаз Скверны'),
(102075, 262416, 1, 21, 1, -1, 28, 191075, 41, 32, 1, 135, 'Summon Familiar: Тусклый Глаз Скверны'),
(102076, 262416, 1, 21, 1, -1, 28, 191076, 41, 32, 1, 3908, 'Summon Familiar: Страж Ужаса'),
(102077, 262416, 1, 21, 1, -1, 28, 191077, 41, 32, 1, 216, 'Summon Familiar: Суккуб-Малышка'),
(102078, 262416, 1, 21, 1, -1, 28, 191078, 41, 32, 1, 214, 'Summon Familiar: Адская Гончая'),
(102079, 262416, 1, 21, 1, -1, 28, 191079, 41, 32, 1, 2795, 'Summon Familiar: Повелитель Преисподней');

-- STEP 2: spell_dbc — positive owner-auras (103xxx, buff bar)
DELETE FROM spell_dbc WHERE ID IN (103070, 103071, 103072, 103073, 103074, 103075, 103076, 103077, 103078, 103079);
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103070, 2147483648, 21, 101, 1, -1, 6, 290, 1, 1, 0, 1, 1, 214, 'Familiar Aura: Ловец Скверны', '+2% шанса критического удара');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103071, 2147483648, 21, 101, 1, -1, 6, 290, 1, 1, 0, 1, 1, 214, 'Familiar Aura: Испуганный Ловец Скверны', '+2% шанса критического удара');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103072, 2147483648, 21, 101, 1, -1, 6, 192, 1, 1, 0, 1, 1, 3171, 'Familiar Aura: Грелль', '+2% скорости атаки');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103073, 2147483648, 21, 101, 1, -1, 6, 192, 1, 1, 0, 1, 1, 3171, 'Familiar Aura: Линялый Грелль', '+2% скорости атаки');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103074, 2147483648, 21, 101, 1, -1, 6, 31, 1, 1, 0, 1, 1, 135, 'Familiar Aura: Глаз Скверны', '+2% скорости передвижения');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103075, 2147483648, 21, 101, 1, -1, 6, 31, 1, 1, 0, 1, 1, 135, 'Familiar Aura: Тусклый Глаз Скверны', '+2% скорости передвижения');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103076, 2147483648, 21, 101, 1, -1, 6, 290, 2, 1, 0, 1, 6, 192, 2, 1, 0, 1, 1, 3908, 'Familiar Aura: Страж Ужаса', '+3% шанса критического удара, +3% скорости атаки');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103077, 2147483648, 21, 101, 1, -1, 6, 290, 3, 1, 0, 1, 6, 31, 4, 1, 0, 1, 1, 216, 'Familiar Aura: Суккуб-Малышка', '+4% шанса критического удара, +5% скорости передвижения');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103078, 2147483648, 21, 101, 1, -1, 6, 192, 2, 1, 0, 1, 6, 65, 2, 1, 0, 1, 1, 214, 'Familiar Aura: Адская Гончая', '+3% скорости атаки, +3% скорости накладывания заклинаний');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, Effect_3, EffectAura_3, EffectBasePoints_3, EffectDieSides_3, EffectMiscValue_3, ImplicitTargetA_3, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103079, 2147483648, 21, 101, 1, -1, 6, 290, 4, 1, 0, 1, 6, 192, 4, 1, 0, 1, 6, 31, 4, 1, 0, 1, 1, 2795, 'Familiar Aura: Повелитель Преисподней', '+5% шанса критического удара, +5% скорости атаки, +5% скорости передвижения');

-- STEP 3: spell_dbc — negative owner-auras (104xxx, debuff bar)
DELETE FROM spell_dbc WHERE ID IN (104071, 104073, 104075, 104079);
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(104071, 2214592512, 21, 101, 1, -1, 6, 137, -2, 1, 2, 1, 1, 214, 'Familiar Debuff: Испуганный Ловец Скверны', '-1% выносливости');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(104073, 2214592512, 21, 101, 1, -1, 6, 137, -3, 1, 4, 1, 1, 3171, 'Familiar Debuff: Линялый Грелль', '-2% духа');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(104075, 2214592512, 21, 101, 1, -1, 6, 137, -2, 1, 2, 1, 1, 135, 'Familiar Debuff: Тусклый Глаз Скверны', '-1% выносливости');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(104079, 2214592512, 21, 101, 1, -1, 6, 22, -6, 1, 16, 1, 6, 137, -6, 1, 2, 1, 1, 2795, 'Familiar Debuff: Повелитель Преисподней', '-5 сопротивления морозу, -5% выносливости');

-- STEP 4: creature_template + _model + _locale
DELETE FROM creature_template_locale WHERE entry IN (191070, 191071, 191072, 191073, 191074, 191075, 191076, 191077, 191078, 191079);
DELETE FROM creature_template_model  WHERE CreatureID IN (191070, 191071, 191072, 191073, 191074, 191075, 191076, 191077, 191078, 191079);
DELETE FROM creature_template        WHERE entry IN (191070, 191071, 191072, 191073, 191074, 191075, 191076, 191077, 191078, 191079);

REPLACE INTO creature_template (entry, name, subname, minlevel, maxlevel, faction, unit_class, type, family, npcflag, AIName) VALUES
(191070, 'Ловец Скверны', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191071, 'Испуганный Ловец Скверны', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191072, 'Грелль', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191073, 'Линялый Грелль', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191074, 'Глаз Скверны', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191075, 'Тусклый Глаз Скверны', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191076, 'Страж Ужаса', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191077, 'Суккуб-Малышка', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191078, 'Адская Гончая', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191079, 'Повелитель Преисподней', '', 1, 1, 35, 1, 7, 0, 0, '');

INSERT INTO creature_template_model (CreatureID, Idx, CreatureDisplayID, DisplayScale, Probability, VerifiedBuild) VALUES
(191070, 0, 850, 1.0, 1, 0),
(191071, 0, 850, 1.0, 1, 0),
(191072, 0, 10816, 0.6, 1, 0),
(191073, 0, 10816, 0.6, 1, 0),
(191074, 0, 65074, 0.8, 1, 0),
(191075, 0, 65075, 0.8, 1, 0),
(191076, 0, 21381, 1.0, 1, 0),
(191077, 0, 159, 1.0, 1, 0),
(191078, 0, 10993, 1.0, 1, 0),
(191079, 0, 10992, 1.0, 1, 0);

INSERT INTO creature_template_locale (entry, locale, Name, Title) VALUES
(191070, 'ruRU', 'Ловец Скверны', ''),
(191071, 'ruRU', 'Испуганный Ловец Скверны', ''),
(191072, 'ruRU', 'Грелль', ''),
(191073, 'ruRU', 'Линялый Грелль', ''),
(191074, 'ruRU', 'Глаз Скверны', ''),
(191075, 'ruRU', 'Тусклый Глаз Скверны', ''),
(191076, 'ruRU', 'Страж Ужаса', ''),
(191077, 'ruRU', 'Суккуб-Малышка', ''),
(191078, 'ruRU', 'Адская Гончая', ''),
(191079, 'ruRU', 'Повелитель Преисподней', '');

-- muted-ambient custom displays (need rows in patched CreatureDisplayInfo.dbc, server+client)
DELETE FROM creature_model_info WHERE DisplayID IN (65074, 65075);
INSERT INTO creature_model_info (DisplayID, BoundingRadius, CombatReach, Gender, DisplayID_Other_Gender)
SELECT 65074, BoundingRadius, CombatReach, Gender, 0 FROM creature_model_info WHERE DisplayID = 14430;
INSERT INTO creature_model_info (DisplayID, BoundingRadius, CombatReach, Gender, DisplayID_Other_Gender)
SELECT 65075, BoundingRadius, CombatReach, Gender, 0 FROM creature_model_info WHERE DisplayID = 14430;

-- STEP 5: item_template (scrolls) + _locale
DELETE FROM item_template_locale WHERE ID IN (110070, 110071, 110072, 110073, 110074, 110075, 110076, 110077, 110078, 110079) AND locale = 'ruRU';
DELETE FROM item_template        WHERE entry IN (110070, 110071, 110072, 110073, 110074, 110075, 110076, 110077, 110078, 110079);

REPLACE INTO item_template (entry, class, subclass, name, displayid, Quality, Flags, BuyPrice, SellPrice, InventoryType, AllowableClass, ItemLevel, RequiredLevel, MaxCount, stackable, spellid_1, spelltrigger_1, spellcharges_1, spellid_2, spelltrigger_2, spellcharges_2, bonding, description, Material) VALUES
(110070, 15, 2, 'Клетка с: Ловец Скверны', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102070, 6, 0, 1, 'Обучает призывать фамильяра: Ловец Скверны. +2% шанса критического удара', 4),
(110071, 15, 2, 'Клетка с: Испуганный Ловец Скверны', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102071, 6, 0, 1, 'Обучает призывать фамильяра: Испуганный Ловец Скверны. +2% шанса критического удара; -1% выносливости', 4),
(110072, 15, 2, 'Клетка с: Грелль', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102072, 6, 0, 1, 'Обучает призывать фамильяра: Грелль. +2% скорости атаки', 4),
(110073, 15, 2, 'Клетка с: Линялый Грелль', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102073, 6, 0, 1, 'Обучает призывать фамильяра: Линялый Грелль. +2% скорости атаки; -2% духа', 4),
(110074, 15, 2, 'Клетка с: Глаз Скверны', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102074, 6, 0, 1, 'Обучает призывать фамильяра: Глаз Скверны. +2% скорости передвижения', 4),
(110075, 15, 2, 'Клетка с: Тусклый Глаз Скверны', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102075, 6, 0, 1, 'Обучает призывать фамильяра: Тусклый Глаз Скверны. +2% скорости передвижения; -1% выносливости', 4),
(110076, 15, 2, 'Клетка с: Страж Ужаса', 58861, 3, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102076, 6, 0, 1, 'Обучает призывать фамильяра: Страж Ужаса. +3% шанса критического удара, +3% скорости атаки', 4),
(110077, 15, 2, 'Клетка с: Суккуб-Малышка', 58861, 3, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102077, 6, 0, 1, 'Обучает призывать фамильяра: Суккуб-Малышка. +4% шанса критического удара, +5% скорости передвижения', 4),
(110078, 15, 2, 'Клетка с: Адская Гончая', 58861, 3, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102078, 6, 0, 1, 'Обучает призывать фамильяра: Адская Гончая. +3% скорости атаки, +3% скорости накладывания заклинаний', 4),
(110079, 15, 2, 'Клетка с: Повелитель Преисподней', 58861, 4, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102079, 6, 0, 1, 'Обучает призывать фамильяра: Повелитель Преисподней. +5% шанса критического удара, +5% скорости атаки, +5% скорости передвижения; -5 сопротивления морозу, -5% выносливости', 4);

INSERT INTO item_template_locale (ID, locale, Name, Description) VALUES
(110070, 'ruRU', 'Клетка с: Ловец Скверны', 'Обучает призывать фамильяра: Ловец Скверны. +2% шанса критического удара'),
(110071, 'ruRU', 'Клетка с: Испуганный Ловец Скверны', 'Обучает призывать фамильяра: Испуганный Ловец Скверны. +2% шанса критического удара; -1% выносливости'),
(110072, 'ruRU', 'Клетка с: Грелль', 'Обучает призывать фамильяра: Грелль. +2% скорости атаки'),
(110073, 'ruRU', 'Клетка с: Линялый Грелль', 'Обучает призывать фамильяра: Линялый Грелль. +2% скорости атаки; -2% духа'),
(110074, 'ruRU', 'Клетка с: Глаз Скверны', 'Обучает призывать фамильяра: Глаз Скверны. +2% скорости передвижения'),
(110075, 'ruRU', 'Клетка с: Тусклый Глаз Скверны', 'Обучает призывать фамильяра: Тусклый Глаз Скверны. +2% скорости передвижения; -1% выносливости'),
(110076, 'ruRU', 'Клетка с: Страж Ужаса', 'Обучает призывать фамильяра: Страж Ужаса. +3% шанса критического удара, +3% скорости атаки'),
(110077, 'ruRU', 'Клетка с: Суккуб-Малышка', 'Обучает призывать фамильяра: Суккуб-Малышка. +4% шанса критического удара, +5% скорости передвижения'),
(110078, 'ruRU', 'Клетка с: Адская Гончая', 'Обучает призывать фамильяра: Адская Гончая. +3% скорости атаки, +3% скорости накладывания заклинаний'),
(110079, 'ruRU', 'Клетка с: Повелитель Преисподней', 'Обучает призывать фамильяра: Повелитель Преисподней. +5% шанса критического удара, +5% скорости атаки, +5% скорости передвижения; -5 сопротивления морозу, -5% выносливости');