-- ============================================================================
-- Nemesis Familiar Gacha — family 6 (Теневой / shadow)
-- AUTO-GENERATED by scripts/familiar-gen-sql.ps1 from 06_shadow.json
-- Do not hand-edit: change the JSON and regenerate.
--
-- amount = EffectBasePoints + 1 (DieSides=1). buff=0x80000000,
-- debuff=0x84000000 (NO_AURA_CANCEL | AURA_IS_DEBUFF). See generator header.
-- ============================================================================

-- STEP 1: spell_dbc — summon spells
DELETE FROM spell_dbc WHERE ID IN (102050, 102051, 102052, 102053, 102054, 102055, 102056, 102057, 102058, 102059);
REPLACE INTO spell_dbc (ID, Attributes, CastingTimeIndex, DurationIndex, RangeIndex, EquippedItemClass, Effect_1, EffectMiscValue_1, EffectMiscValueB_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS) VALUES
(102050, 262416, 1, 21, 1, -1, 28, 191050, 41, 32, 1, 1577, 'Summon Familiar: Нетопырь'),
(102051, 262416, 1, 21, 1, -1, 28, 191051, 41, 32, 1, 1577, 'Summon Familiar: Облезлый Нетопырь'),
(102052, 262416, 1, 21, 1, -1, 28, 191052, 41, 32, 1, 3905, 'Summon Familiar: Тёмный Таракан'),
(102053, 262416, 1, 21, 1, -1, 28, 191053, 41, 32, 1, 3905, 'Summon Familiar: Таракан'),
(102054, 262416, 1, 21, 1, -1, 28, 191054, 41, 32, 1, 3907, 'Summon Familiar: Бубонная Крыса'),
(102055, 262416, 1, 21, 1, -1, 28, 191055, 41, 32, 1, 3907, 'Summon Familiar: Дохлая Крыса'),
(102056, 262416, 1, 21, 1, -1, 28, 191056, 41, 32, 1, 3932, 'Summon Familiar: Слуга Тьмы'),
(102057, 262416, 1, 21, 1, -1, 28, 191057, 41, 32, 1, 1747, 'Summon Familiar: Чумной Жнец'),
(102058, 262416, 1, 21, 1, -1, 28, 191058, 41, 32, 1, 1611, 'Summon Familiar: Услужливый Шептун'),
(102059, 262416, 1, 21, 1, -1, 28, 191059, 41, 32, 1, 4075, 'Summon Familiar: Лик Сумрака');

-- STEP 2: spell_dbc — positive owner-auras (103xxx, buff bar)
DELETE FROM spell_dbc WHERE ID IN (103050, 103051, 103052, 103053, 103054, 103055, 103056, 103057, 103058, 103059);
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103050, 2147483648, 21, 101, 1, -1, 6, 79, 1, 1, 32, 1, 1, 1577, 'Familiar Aura: Нетопырь', '+2% урона тенью');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103051, 2147483648, 21, 101, 1, -1, 6, 79, 1, 1, 32, 1, 1, 1577, 'Familiar Aura: Облезлый Нетопырь', '+2% урона тенью');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103052, 2147483648, 21, 101, 1, -1, 6, 137, 0, 1, 3, 1, 1, 3905, 'Familiar Aura: Тёмный Таракан', '+1% интеллекта');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103053, 2147483648, 21, 101, 1, -1, 6, 137, 0, 1, 3, 1, 1, 3905, 'Familiar Aura: Таракан', '+1% интеллекта');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103054, 2147483648, 21, 101, 1, -1, 6, 22, 1, 1, 126, 1, 1, 3907, 'Familiar Aura: Бубонная Крыса', '+2 сопротивления всем школам магии');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103055, 2147483648, 21, 101, 1, -1, 6, 22, 1, 1, 126, 1, 1, 3907, 'Familiar Aura: Дохлая Крыса', '+2 сопротивления всем школам магии');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103056, 2147483648, 21, 101, 1, -1, 6, 79, 4, 1, 32, 1, 6, 65, 2, 1, 0, 1, 1, 3932, 'Familiar Aura: Слуга Тьмы', '+5% урона тенью, +3% скорости накладывания заклинаний');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103057, 2147483648, 21, 101, 1, -1, 6, 79, 4, 1, 32, 1, 6, 137, 2, 1, 3, 1, 1, 1747, 'Familiar Aura: Чумной Жнец', '+5% урона тенью, +3% интеллекта');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103058, 2147483648, 21, 101, 1, -1, 6, 79, 4, 1, 32, 1, 6, 49, 2, 1, 0, 1, 1, 1611, 'Familiar Aura: Услужливый Шептун', '+5% урона тенью, +3% уворота');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, Effect_3, EffectAura_3, EffectBasePoints_3, EffectDieSides_3, EffectMiscValue_3, ImplicitTargetA_3, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103059, 2147483648, 21, 101, 1, -1, 6, 79, 9, 1, 32, 1, 6, 137, 4, 1, 3, 1, 6, 22, 4, 1, 32, 1, 1, 4075, 'Familiar Aura: Лик Сумрака', '+10% урона тенью, +5% интеллекта, +5 сопротивления тени');

-- STEP 3: spell_dbc — negative owner-auras (104xxx, debuff bar)
DELETE FROM spell_dbc WHERE ID IN (104051, 104053, 104055, 104059);
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(104051, 2214592512, 21, 101, 1, -1, 6, 137, -2, 1, 3, 1, 1, 1577, 'Familiar Debuff: Облезлый Нетопырь', '-1% интеллекта');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(104053, 2214592512, 21, 101, 1, -1, 6, 31, -2, 1, 0, 1, 1, 3905, 'Familiar Debuff: Таракан', '-1% скорости передвижения');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(104055, 2214592512, 21, 101, 1, -1, 6, 137, -2, 1, 2, 1, 1, 3907, 'Familiar Debuff: Дохлая Крыса', '-1% выносливости');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(104059, 2214592512, 21, 101, 1, -1, 6, 22, -11, 1, 8, 1, 6, 137, -6, 1, 2, 1, 1, 4075, 'Familiar Debuff: Лик Сумрака', '-10 сопротивления природе, -5% выносливости');

-- STEP 4: creature_template + _model + _locale
DELETE FROM creature_template_locale WHERE entry IN (191050, 191051, 191052, 191053, 191054, 191055, 191056, 191057, 191058, 191059);
DELETE FROM creature_template_model  WHERE CreatureID IN (191050, 191051, 191052, 191053, 191054, 191055, 191056, 191057, 191058, 191059);
DELETE FROM creature_template        WHERE entry IN (191050, 191051, 191052, 191053, 191054, 191055, 191056, 191057, 191058, 191059);

REPLACE INTO creature_template (entry, name, subname, minlevel, maxlevel, faction, unit_class, type, family, npcflag, AIName) VALUES
(191050, 'Нетопырь', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191051, 'Облезлый Нетопырь', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191052, 'Тёмный Таракан', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191053, 'Таракан', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191054, 'Бубонная Крыса', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191055, 'Дохлая Крыса', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191056, 'Слуга Тьмы', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191057, 'Чумной Жнец', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191058, 'Услужливый Шептун', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191059, 'Лик Сумрака', '', 1, 1, 35, 1, 7, 0, 0, '');

INSERT INTO creature_template_model (CreatureID, Idx, CreatureDisplayID, DisplayScale, Probability, VerifiedBuild) VALUES
(191050, 0, 4185, 1.0, 1, 0),
(191051, 0, 4185, 1.0, 1, 0),
(191052, 0, 3233, 1.0, 1, 0),
(191053, 0, 3233, 1.0, 1, 0),
(191054, 0, 22175, 1.0, 1, 0),
(191055, 0, 22175, 1.0, 1, 0),
(191056, 0, 29404, 1.0, 1, 0),
(191057, 0, 21900, 1.0, 1, 0),
(191058, 0, 28089, 1.0, 1, 0),
(191059, 0, 30507, 1.0, 1, 0);

INSERT INTO creature_template_locale (entry, locale, Name, Title) VALUES
(191050, 'ruRU', 'Нетопырь', ''),
(191051, 'ruRU', 'Облезлый Нетопырь', ''),
(191052, 'ruRU', 'Тёмный Таракан', ''),
(191053, 'ruRU', 'Таракан', ''),
(191054, 'ruRU', 'Бубонная Крыса', ''),
(191055, 'ruRU', 'Дохлая Крыса', ''),
(191056, 'ruRU', 'Слуга Тьмы', ''),
(191057, 'ruRU', 'Чумной Жнец', ''),
(191058, 'ruRU', 'Услужливый Шептун', ''),
(191059, 'ruRU', 'Лик Сумрака', '');

-- STEP 5: item_template (scrolls) + _locale
DELETE FROM item_template_locale WHERE ID IN (110050, 110051, 110052, 110053, 110054, 110055, 110056, 110057, 110058, 110059) AND locale = 'ruRU';
DELETE FROM item_template        WHERE entry IN (110050, 110051, 110052, 110053, 110054, 110055, 110056, 110057, 110058, 110059);

REPLACE INTO item_template (entry, class, subclass, name, displayid, Quality, Flags, BuyPrice, SellPrice, InventoryType, AllowableClass, ItemLevel, RequiredLevel, MaxCount, stackable, spellid_1, spelltrigger_1, spellcharges_1, spellid_2, spelltrigger_2, spellcharges_2, bonding, description, Material) VALUES
(110050, 15, 2, 'Клетка с: Нетопырь', 20629, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102050, 6, 0, 1, 'Обучает призывать фамильяра: Нетопырь. +2% урона тенью', 4),
(110051, 15, 2, 'Клетка с: Облезлый Нетопырь', 20629, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102051, 6, 0, 1, 'Обучает призывать фамильяра: Облезлый Нетопырь. +2% урона тенью; -1% интеллекта', 4),
(110052, 15, 2, 'Клетка с: Тёмный Таракан', 20629, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102052, 6, 0, 1, 'Обучает призывать фамильяра: Тёмный Таракан. +1% интеллекта', 4),
(110053, 15, 2, 'Клетка с: Таракан', 20629, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102053, 6, 0, 1, 'Обучает призывать фамильяра: Таракан. +1% интеллекта; -1% скорости передвижения', 4),
(110054, 15, 2, 'Клетка с: Бубонная Крыса', 20629, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102054, 6, 0, 1, 'Обучает призывать фамильяра: Бубонная Крыса. +2 сопротивления всем школам магии', 4),
(110055, 15, 2, 'Клетка с: Дохлая Крыса', 20629, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102055, 6, 0, 1, 'Обучает призывать фамильяра: Дохлая Крыса. +2 сопротивления всем школам магии; -1% выносливости', 4),
(110056, 15, 2, 'Клетка с: Слуга Тьмы', 20629, 3, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102056, 6, 0, 1, 'Обучает призывать фамильяра: Слуга Тьмы. +5% урона тенью, +3% скорости накладывания заклинаний', 4),
(110057, 15, 2, 'Клетка с: Чумной Жнец', 20629, 3, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102057, 6, 0, 1, 'Обучает призывать фамильяра: Чумной Жнец. +5% урона тенью, +3% интеллекта', 4),
(110058, 15, 2, 'Клетка с: Услужливый Шептун', 20629, 3, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102058, 6, 0, 1, 'Обучает призывать фамильяра: Услужливый Шептун. +5% урона тенью, +3% уворота', 4),
(110059, 15, 2, 'Клетка с: Лик Сумрака', 20629, 4, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102059, 6, 0, 1, 'Обучает призывать фамильяра: Лик Сумрака. +10% урона тенью, +5% интеллекта, +5 сопротивления тени; -10 сопротивления природе, -5% выносливости', 4);

INSERT INTO item_template_locale (ID, locale, Name, Description) VALUES
(110050, 'ruRU', 'Клетка с: Нетопырь', 'Обучает призывать фамильяра: Нетопырь. +2% урона тенью'),
(110051, 'ruRU', 'Клетка с: Облезлый Нетопырь', 'Обучает призывать фамильяра: Облезлый Нетопырь. +2% урона тенью; -1% интеллекта'),
(110052, 'ruRU', 'Клетка с: Тёмный Таракан', 'Обучает призывать фамильяра: Тёмный Таракан. +1% интеллекта'),
(110053, 'ruRU', 'Клетка с: Таракан', 'Обучает призывать фамильяра: Таракан. +1% интеллекта; -1% скорости передвижения'),
(110054, 'ruRU', 'Клетка с: Бубонная Крыса', 'Обучает призывать фамильяра: Бубонная Крыса. +2 сопротивления всем школам магии'),
(110055, 'ruRU', 'Клетка с: Дохлая Крыса', 'Обучает призывать фамильяра: Дохлая Крыса. +2 сопротивления всем школам магии; -1% выносливости'),
(110056, 'ruRU', 'Клетка с: Слуга Тьмы', 'Обучает призывать фамильяра: Слуга Тьмы. +5% урона тенью, +3% скорости накладывания заклинаний'),
(110057, 'ruRU', 'Клетка с: Чумной Жнец', 'Обучает призывать фамильяра: Чумной Жнец. +5% урона тенью, +3% интеллекта'),
(110058, 'ruRU', 'Клетка с: Услужливый Шептун', 'Обучает призывать фамильяра: Услужливый Шептун. +5% урона тенью, +3% уворота'),
(110059, 'ruRU', 'Клетка с: Лик Сумрака', 'Обучает призывать фамильяра: Лик Сумрака. +10% урона тенью, +5% интеллекта, +5 сопротивления тени; -10 сопротивления природе, -5% выносливости');