-- ============================================================================
-- Nemesis Familiar Gacha — family 7 (Тайный / arcane)
-- AUTO-GENERATED by scripts/familiar-gen-sql.ps1 from 07_arcane.json
-- Do not hand-edit: change the JSON and regenerate.
--
-- amount = EffectBasePoints + 1 (DieSides=1). buff=0x80000000,
-- debuff=0x84000000 (NO_AURA_CANCEL | AURA_IS_DEBUFF). See generator header.
-- ============================================================================

-- STEP 1: spell_dbc — summon spells
DELETE FROM spell_dbc WHERE ID IN (102060, 102061, 102062, 102063, 102064, 102065, 102066, 102067, 102068, 102069);
REPLACE INTO spell_dbc (ID, Attributes, CastingTimeIndex, DurationIndex, RangeIndex, EquippedItemClass, Effect_1, EffectMiscValue_1, EffectMiscValueB_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS) VALUES
(102060, 262416, 1, 21, 1, -1, 28, 191060, 41, 32, 1, 2383, 'Summon Familiar: Манчик'),
(102061, 262416, 1, 21, 1, -1, 28, 191061, 41, 32, 1, 2383, 'Summon Familiar: Истощённый Манчик'),
(102062, 262416, 1, 21, 1, -1, 28, 191062, 41, 32, 1, 2328, 'Summon Familiar: Малый Дракондор'),
(102063, 262416, 1, 21, 1, -1, 28, 191063, 41, 32, 1, 2328, 'Summon Familiar: Побитый Дракондор'),
(102064, 262416, 1, 21, 1, -1, 28, 191064, 41, 32, 1, 1502, 'Summon Familiar: Подметалка'),
(102065, 262416, 1, 21, 1, -1, 28, 191065, 41, 32, 1, 1502, 'Summon Familiar: Сломанная Подметалка'),
(102066, 262416, 1, 21, 1, -1, 28, 191066, 41, 32, 1, 1677, 'Summon Familiar: Эфириальный Дух'),
(102067, 262416, 1, 21, 1, -1, 28, 191067, 41, 32, 1, 2449, 'Summon Familiar: Звёздный Дракон'),
(102068, 262416, 1, 21, 1, -1, 28, 191068, 41, 32, 1, 1910, 'Summon Familiar: Лунный Хранитель'),
(102069, 262416, 1, 21, 1, -1, 28, 191069, 41, 32, 1, 1928, 'Summon Familiar: Звёздный Дух');

-- STEP 2: spell_dbc — positive owner-auras (103xxx, buff bar)
DELETE FROM spell_dbc WHERE ID IN (103060, 103061, 103062, 103063, 103064, 103065, 103066, 103067, 103068, 103069);
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103060, 2147483648, 21, 101, 1, -1, 6, 79, 1, 1, 64, 1, 1, 2383, 'Familiar Aura: Манчик', '+2% урона тайной магией');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103061, 2147483648, 21, 101, 1, -1, 6, 79, 1, 1, 64, 1, 1, 2383, 'Familiar Aura: Истощённый Манчик', '+2% урона тайной магией');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103062, 2147483648, 21, 101, 1, -1, 6, 137, 1, 1, 3, 1, 1, 2328, 'Familiar Aura: Малый Дракондор', '+2% интеллекта');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103063, 2147483648, 21, 101, 1, -1, 6, 137, 1, 1, 3, 1, 1, 2328, 'Familiar Aura: Побитый Дракондор', '+2% интеллекта');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103064, 2147483648, 21, 101, 1, -1, 6, 65, 1, 1, 0, 1, 1, 1502, 'Familiar Aura: Подметалка', '+2% скорости накладывания заклинаний');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103065, 2147483648, 21, 101, 1, -1, 6, 65, 1, 1, 0, 1, 1, 1502, 'Familiar Aura: Сломанная Подметалка', '+2% скорости накладывания заклинаний');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103066, 2147483648, 21, 101, 1, -1, 6, 79, 4, 1, 64, 1, 6, 65, 2, 1, 0, 1, 1, 1677, 'Familiar Aura: Эфириальный Дух', '+5% урона тайной магией, +3% скорости накладывания заклинаний');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103067, 2147483648, 21, 101, 1, -1, 6, 79, 4, 1, 64, 1, 6, 137, 2, 1, 3, 1, 1, 2449, 'Familiar Aura: Звёздный Дракон', '+5% урона тайной магией, +3% интеллекта');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103068, 2147483648, 21, 101, 1, -1, 6, 79, 4, 1, 64, 1, 6, 137, 2, 1, 4, 1, 1, 1910, 'Familiar Aura: Лунный Хранитель', '+5% урона тайной магией, +3% духа');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, Effect_3, EffectAura_3, EffectBasePoints_3, EffectDieSides_3, EffectMiscValue_3, ImplicitTargetA_3, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103069, 2147483648, 21, 101, 1, -1, 6, 79, 9, 1, 64, 1, 6, 57, 4, 1, 0, 1, 6, 137, 4, 1, 3, 1, 1, 1928, 'Familiar Aura: Звёздный Дух', '+10% урона тайной магией, +5% шанса критического удара заклинаний, +5% интеллекта');

-- STEP 3: spell_dbc — negative owner-auras (104xxx, debuff bar)
DELETE FROM spell_dbc WHERE ID IN (104061, 104063, 104065, 104069);
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(104061, 2214592512, 21, 101, 1, -1, 6, 137, -2, 1, 4, 1, 1, 2383, 'Familiar Debuff: Истощённый Манчик', '-1% духа');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(104063, 2214592512, 21, 101, 1, -1, 6, 137, -3, 1, 4, 1, 1, 2328, 'Familiar Debuff: Побитый Дракондор', '-2% духа');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(104065, 2214592512, 21, 101, 1, -1, 6, 137, -2, 1, 2, 1, 1, 1502, 'Familiar Debuff: Сломанная Подметалка', '-1% выносливости');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, Effect_3, EffectAura_3, EffectBasePoints_3, EffectDieSides_3, EffectMiscValue_3, ImplicitTargetA_3, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(104069, 2214592512, 21, 101, 1, -1, 6, 22, -6, 1, 4, 1, 6, 22, -6, 1, 16, 1, 6, 137, -6, 1, 2, 1, 1, 1928, 'Familiar Debuff: Звёздный Дух', '-5 сопротивления огню, -5 сопротивления морозу, -5% выносливости');

-- STEP 4: creature_template + _model + _locale
DELETE FROM creature_template_locale WHERE entry IN (191060, 191061, 191062, 191063, 191064, 191065, 191066, 191067, 191068, 191069);
DELETE FROM creature_template_model  WHERE CreatureID IN (191060, 191061, 191062, 191063, 191064, 191065, 191066, 191067, 191068, 191069);
DELETE FROM creature_template        WHERE entry IN (191060, 191061, 191062, 191063, 191064, 191065, 191066, 191067, 191068, 191069);

REPLACE INTO creature_template (entry, name, subname, minlevel, maxlevel, faction, unit_class, type, family, npcflag, AIName) VALUES
(191060, 'Манчик', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191061, 'Истощённый Манчик', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191062, 'Малый Дракондор', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191063, 'Побитый Дракондор', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191064, 'Подметалка', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191065, 'Сломанная Подметалка', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191066, 'Эфириальный Дух', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191067, 'Звёздный Дракон', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191068, 'Лунный Хранитель', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191069, 'Звёздный Дух', '', 1, 1, 35, 1, 7, 0, 0, '');

INSERT INTO creature_template_model (CreatureID, Idx, CreatureDisplayID, DisplayScale, Probability, VerifiedBuild) VALUES
(191060, 0, 29372, 1.0, 1, 0),
(191061, 0, 29372, 1.0, 1, 0),
(191062, 0, 20029, 1.0, 1, 0),
(191063, 0, 20029, 1.0, 1, 0),
(191064, 0, 65064, 1.0, 1, 0),
(191065, 0, 65065, 1.0, 1, 0),
(191066, 0, 65066, 0.7, 1, 0),
(191067, 0, 17723, 1.0, 1, 0),
(191068, 0, 14273, 1.0, 1, 0),
(191069, 0, 31956, 1.0, 1, 0);

INSERT INTO creature_template_locale (entry, locale, Name, Title) VALUES
(191060, 'ruRU', 'Манчик', ''),
(191061, 'ruRU', 'Истощённый Манчик', ''),
(191062, 'ruRU', 'Малый Дракондор', ''),
(191063, 'ruRU', 'Побитый Дракондор', ''),
(191064, 'ruRU', 'Подметалка', ''),
(191065, 'ruRU', 'Сломанная Подметалка', ''),
(191066, 'ruRU', 'Эфириальный Дух', ''),
(191067, 'ruRU', 'Звёздный Дракон', ''),
(191068, 'ruRU', 'Лунный Хранитель', ''),
(191069, 'ruRU', 'Звёздный Дух', '');

-- muted-ambient custom displays (need rows in patched CreatureDisplayInfo.dbc, server+client)
DELETE FROM creature_model_info WHERE DisplayID IN (65064, 65065, 65066);
INSERT INTO creature_model_info (DisplayID, BoundingRadius, CombatReach, Gender, DisplayID_Other_Gender)
SELECT 65064, BoundingRadius, CombatReach, Gender, 0 FROM creature_model_info WHERE DisplayID = 16910;
INSERT INTO creature_model_info (DisplayID, BoundingRadius, CombatReach, Gender, DisplayID_Other_Gender)
SELECT 65065, BoundingRadius, CombatReach, Gender, 0 FROM creature_model_info WHERE DisplayID = 16910;
INSERT INTO creature_model_info (DisplayID, BoundingRadius, CombatReach, Gender, DisplayID_Other_Gender)
SELECT 65066, BoundingRadius, CombatReach, Gender, 0 FROM creature_model_info WHERE DisplayID = 25002;

-- STEP 5: item_template (scrolls) + _locale
DELETE FROM item_template_locale WHERE ID IN (110060, 110061, 110062, 110063, 110064, 110065, 110066, 110067, 110068, 110069) AND locale = 'ruRU';
DELETE FROM item_template        WHERE entry IN (110060, 110061, 110062, 110063, 110064, 110065, 110066, 110067, 110068, 110069);

REPLACE INTO item_template (entry, class, subclass, name, displayid, Quality, Flags, BuyPrice, SellPrice, InventoryType, AllowableClass, ItemLevel, RequiredLevel, MaxCount, stackable, spellid_1, spelltrigger_1, spellcharges_1, spellid_2, spelltrigger_2, spellcharges_2, bonding, description, Material) VALUES
(110060, 15, 2, 'Клетка с: Манчик', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102060, 6, 0, 1, 'Обучает призывать фамильяра: Манчик. +2% урона тайной магией', 4),
(110061, 15, 2, 'Клетка с: Истощённый Манчик', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102061, 6, 0, 1, 'Обучает призывать фамильяра: Истощённый Манчик. +2% урона тайной магией; -1% духа', 4),
(110062, 15, 2, 'Клетка с: Малый Дракондор', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102062, 6, 0, 1, 'Обучает призывать фамильяра: Малый Дракондор. +2% интеллекта', 4),
(110063, 15, 2, 'Клетка с: Побитый Дракондор', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102063, 6, 0, 1, 'Обучает призывать фамильяра: Побитый Дракондор. +2% интеллекта; -2% духа', 4),
(110064, 15, 2, 'Клетка с: Подметалка', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102064, 6, 0, 1, 'Обучает призывать фамильяра: Подметалка. +2% скорости накладывания заклинаний', 4),
(110065, 15, 2, 'Клетка с: Сломанная Подметалка', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102065, 6, 0, 1, 'Обучает призывать фамильяра: Сломанная Подметалка. +2% скорости накладывания заклинаний; -1% выносливости', 4),
(110066, 15, 2, 'Клетка с: Эфириальный Дух', 58861, 3, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102066, 6, 0, 1, 'Обучает призывать фамильяра: Эфириальный Дух. +5% урона тайной магией, +3% скорости накладывания заклинаний', 4),
(110067, 15, 2, 'Клетка с: Звёздный Дракон', 58861, 3, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102067, 6, 0, 1, 'Обучает призывать фамильяра: Звёздный Дракон. +5% урона тайной магией, +3% интеллекта', 4),
(110068, 15, 2, 'Клетка с: Лунный Хранитель', 58861, 3, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102068, 6, 0, 1, 'Обучает призывать фамильяра: Лунный Хранитель. +5% урона тайной магией, +3% духа', 4),
(110069, 15, 2, 'Клетка с: Звёздный Дух', 58861, 4, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102069, 6, 0, 1, 'Обучает призывать фамильяра: Звёздный Дух. +10% урона тайной магией, +5% шанса критического удара заклинаний, +5% интеллекта; -5 сопротивления огню, -5 сопротивления морозу, -5% выносливости', 4);

INSERT INTO item_template_locale (ID, locale, Name, Description) VALUES
(110060, 'ruRU', 'Клетка с: Манчик', 'Обучает призывать фамильяра: Манчик. +2% урона тайной магией'),
(110061, 'ruRU', 'Клетка с: Истощённый Манчик', 'Обучает призывать фамильяра: Истощённый Манчик. +2% урона тайной магией; -1% духа'),
(110062, 'ruRU', 'Клетка с: Малый Дракондор', 'Обучает призывать фамильяра: Малый Дракондор. +2% интеллекта'),
(110063, 'ruRU', 'Клетка с: Побитый Дракондор', 'Обучает призывать фамильяра: Побитый Дракондор. +2% интеллекта; -2% духа'),
(110064, 'ruRU', 'Клетка с: Подметалка', 'Обучает призывать фамильяра: Подметалка. +2% скорости накладывания заклинаний'),
(110065, 'ruRU', 'Клетка с: Сломанная Подметалка', 'Обучает призывать фамильяра: Сломанная Подметалка. +2% скорости накладывания заклинаний; -1% выносливости'),
(110066, 'ruRU', 'Клетка с: Эфириальный Дух', 'Обучает призывать фамильяра: Эфириальный Дух. +5% урона тайной магией, +3% скорости накладывания заклинаний'),
(110067, 'ruRU', 'Клетка с: Звёздный Дракон', 'Обучает призывать фамильяра: Звёздный Дракон. +5% урона тайной магией, +3% интеллекта'),
(110068, 'ruRU', 'Клетка с: Лунный Хранитель', 'Обучает призывать фамильяра: Лунный Хранитель. +5% урона тайной магией, +3% духа'),
(110069, 'ruRU', 'Клетка с: Звёздный Дух', 'Обучает призывать фамильяра: Звёздный Дух. +10% урона тайной магией, +5% шанса критического удара заклинаний, +5% интеллекта; -5 сопротивления огню, -5 сопротивления морозу, -5% выносливости');