-- ============================================================================
-- Nemesis Familiar Gacha — family 4 (Природный / nature)
-- AUTO-GENERATED by scripts/familiar-gen-sql.ps1 from 04_nature.json
-- Do not hand-edit: change the JSON and regenerate.
--
-- amount = EffectBasePoints + 1 (DieSides=1). buff=0x80000000,
-- debuff=0x84000000 (NO_AURA_CANCEL | AURA_IS_DEBUFF). See generator header.
-- ============================================================================

-- STEP 1: spell_dbc — summon spells
DELETE FROM spell_dbc WHERE ID IN (102030, 102031, 102032, 102033, 102034, 102035, 102036, 102037, 102038, 102039);
REPLACE INTO spell_dbc (ID, Attributes, CastingTimeIndex, DurationIndex, RangeIndex, EquippedItemClass, Effect_1, EffectMiscValue_1, EffectMiscValueB_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS) VALUES
(102030, 262416, 1, 21, 1, -1, 28, 191030, 41, 32, 1, 122, 'Summon Familiar: Светлячок'),
(102031, 262416, 1, 21, 1, -1, 28, 191031, 41, 32, 1, 122, 'Summon Familiar: Угасший Светлячок'),
(102032, 262416, 1, 21, 1, -1, 28, 191032, 41, 32, 1, 3088, 'Summon Familiar: Лесной дух'),
(102033, 262416, 1, 21, 1, -1, 28, 191033, 41, 32, 1, 3088, 'Summon Familiar: Заблудший лесной дух'),
(102034, 262416, 1, 21, 1, -1, 28, 191034, 41, 32, 1, 2585, 'Summon Familiar: Корешок'),
(102035, 262416, 1, 21, 1, -1, 28, 191035, 41, 32, 1, 2585, 'Summon Familiar: Высохший Корешок'),
(102036, 262416, 1, 21, 1, -1, 28, 191036, 41, 32, 1, 1702, 'Summon Familiar: Изумрудный дракон'),
(102037, 262416, 1, 21, 1, -1, 28, 191037, 41, 32, 1, 1514, 'Summon Familiar: Детеныш хамелеона'),
(102038, 262416, 1, 21, 1, -1, 28, 191038, 41, 32, 1, 1217, 'Summon Familiar: Древник-Хранитель'),
(102039, 262416, 1, 21, 1, -1, 28, 191039, 41, 32, 1, 2258, 'Summon Familiar: Дух Древа');

-- STEP 2: spell_dbc — positive owner-auras (103xxx, buff bar)
DELETE FROM spell_dbc WHERE ID IN (103030, 103031, 103032, 103033, 103034, 103035, 103036, 103037, 103038, 103039);
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103030, 2147483648, 21, 101, 1, -1, 6, 136, 1, 1, 0, 1, 1, 122, 'Familiar Aura: Светлячок', '+2% исходящего лечения');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103031, 2147483648, 21, 101, 1, -1, 6, 136, 1, 1, 0, 1, 1, 122, 'Familiar Aura: Угасший Светлячок', '+2% исходящего лечения');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103032, 2147483648, 21, 101, 1, -1, 6, 137, 1, 1, 4, 1, 1, 3088, 'Familiar Aura: Лесной дух', '+2% духа');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103033, 2147483648, 21, 101, 1, -1, 6, 137, 1, 1, 4, 1, 1, 3088, 'Familiar Aura: Заблудший лесной дух', '+2% духа');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103034, 2147483648, 21, 101, 1, -1, 6, 22, 2, 1, 126, 1, 1, 2585, 'Familiar Aura: Корешок', '+3 сопротивления всем школам магии');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103035, 2147483648, 21, 101, 1, -1, 6, 22, 2, 1, 126, 1, 1, 2585, 'Familiar Aura: Высохший Корешок', '+3 сопротивления всем школам магии');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103036, 2147483648, 21, 101, 1, -1, 6, 136, 4, 1, 0, 1, 6, 110, 2, 1, 0, 1, 1, 1702, 'Familiar Aura: Изумрудный дракон', '+5% исходящего лечения, +3% восстановления маны');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103037, 2147483648, 21, 101, 1, -1, 6, 136, 4, 1, 0, 1, 6, 137, 2, 1, 3, 1, 1, 1514, 'Familiar Aura: Детеныш хамелеона', '+5% исходящего лечения, +3% интеллекта');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103038, 2147483648, 21, 101, 1, -1, 6, 136, 4, 1, 0, 1, 6, 22, 4, 1, 8, 1, 1, 1217, 'Familiar Aura: Древник-Хранитель', '+5% исходящего лечения, +5 сопротивления природе');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, Effect_3, EffectAura_3, EffectBasePoints_3, EffectDieSides_3, EffectMiscValue_3, ImplicitTargetA_3, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103039, 2147483648, 21, 101, 1, -1, 6, 136, 9, 1, 0, 1, 6, 137, 4, 1, 4, 1, 6, 137, 4, 1, 3, 1, 1, 2258, 'Familiar Aura: Дух Древа', '+10% исходящего лечения, +5% духа, +5% интеллекта');

-- STEP 3: spell_dbc — negative owner-auras (104xxx, debuff bar)
DELETE FROM spell_dbc WHERE ID IN (104031, 104033, 104035, 104039);
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(104031, 2214592512, 21, 101, 1, -1, 6, 137, -2, 1, 3, 1, 1, 122, 'Familiar Debuff: Угасший Светлячок', '-1% интеллекта');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(104033, 2214592512, 21, 101, 1, -1, 6, 31, -2, 1, 0, 1, 1, 3088, 'Familiar Debuff: Заблудший лесной дух', '-1% скорости передвижения');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(104035, 2214592512, 21, 101, 1, -1, 6, 137, -2, 1, 4, 1, 1, 2585, 'Familiar Debuff: Высохший Корешок', '-1% духа');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(104039, 2214592512, 21, 101, 1, -1, 6, 22, -11, 1, 32, 1, 6, 137, -6, 1, 2, 1, 1, 2258, 'Familiar Debuff: Дух Древа', '-10 сопротивления тени, -5% выносливости');

-- STEP 4: creature_template + _model + _locale
DELETE FROM creature_template_locale WHERE entry IN (191030, 191031, 191032, 191033, 191034, 191035, 191036, 191037, 191038, 191039);
DELETE FROM creature_template_model  WHERE CreatureID IN (191030, 191031, 191032, 191033, 191034, 191035, 191036, 191037, 191038, 191039);
DELETE FROM creature_template        WHERE entry IN (191030, 191031, 191032, 191033, 191034, 191035, 191036, 191037, 191038, 191039);

REPLACE INTO creature_template (entry, name, subname, minlevel, maxlevel, faction, unit_class, type, family, npcflag, AIName) VALUES
(191030, 'Светлячок', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191031, 'Угасший Светлячок', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191032, 'Лесной дух', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191033, 'Заблудший лесной дух', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191034, 'Корешок', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191035, 'Высохший Корешок', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191036, 'Изумрудный дракон', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191037, 'Детеныш хамелеона', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191038, 'Древник-Хранитель', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191039, 'Дух Древа', '', 1, 1, 35, 1, 7, 0, 0, '');

INSERT INTO creature_template_model (CreatureID, Idx, CreatureDisplayID, DisplayScale, Probability, VerifiedBuild) VALUES
(191030, 0, 16587, 1.0, 1, 0),
(191031, 0, 16587, 1.0, 1, 0),
(191032, 0, 65032, 1.0, 1, 0),
(191033, 0, 65033, 1.0, 1, 0),
(191034, 0, 28493, 1.0, 1, 0),
(191035, 0, 28493, 1.0, 1, 0),
(191036, 0, 6291, 1.0, 1, 0),
(191037, 0, 6294, 1.0, 1, 0),
(191038, 0, 28482, 1.0, 1, 0),
(191039, 0, 8824, 0.3, 1, 0);

INSERT INTO creature_template_locale (entry, locale, Name, Title) VALUES
(191030, 'ruRU', 'Светлячок', ''),
(191031, 'ruRU', 'Угасший Светлячок', ''),
(191032, 'ruRU', 'Лесной дух', ''),
(191033, 'ruRU', 'Заблудший лесной дух', ''),
(191034, 'ruRU', 'Корешок', ''),
(191035, 'ruRU', 'Высохший Корешок', ''),
(191036, 'ruRU', 'Изумрудный дракон', ''),
(191037, 'ruRU', 'Детеныш хамелеона', ''),
(191038, 'ruRU', 'Древник-Хранитель', ''),
(191039, 'ruRU', 'Дух Древа', '');

-- muted-ambient custom displays (need rows in patched CreatureDisplayInfo.dbc, server+client)
DELETE FROM creature_model_info WHERE DisplayID IN (65032, 65033);
INSERT INTO creature_model_info (DisplayID, BoundingRadius, CombatReach, Gender, DisplayID_Other_Gender)
SELECT 65032, BoundingRadius, CombatReach, Gender, 0 FROM creature_model_info WHERE DisplayID = 24465;
INSERT INTO creature_model_info (DisplayID, BoundingRadius, CombatReach, Gender, DisplayID_Other_Gender)
SELECT 65033, BoundingRadius, CombatReach, Gender, 0 FROM creature_model_info WHERE DisplayID = 24465;

-- STEP 5: item_template (scrolls) + _locale
DELETE FROM item_template_locale WHERE ID IN (110030, 110031, 110032, 110033, 110034, 110035, 110036, 110037, 110038, 110039) AND locale = 'ruRU';
DELETE FROM item_template        WHERE entry IN (110030, 110031, 110032, 110033, 110034, 110035, 110036, 110037, 110038, 110039);

REPLACE INTO item_template (entry, class, subclass, name, displayid, Quality, Flags, BuyPrice, SellPrice, InventoryType, AllowableClass, ItemLevel, RequiredLevel, MaxCount, stackable, spellid_1, spelltrigger_1, spellcharges_1, spellid_2, spelltrigger_2, spellcharges_2, bonding, description, Material) VALUES
(110030, 15, 2, 'Клетка с: Светлячок', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102030, 6, 0, 1, 'Обучает призывать фамильяра: Светлячок. +2% исходящего лечения', 4),
(110031, 15, 2, 'Клетка с: Угасший Светлячок', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102031, 6, 0, 1, 'Обучает призывать фамильяра: Угасший Светлячок. +2% исходящего лечения; -1% интеллекта', 4),
(110032, 15, 2, 'Клетка с: Лесной дух', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102032, 6, 0, 1, 'Обучает призывать фамильяра: Лесной дух. +2% духа', 4),
(110033, 15, 2, 'Клетка с: Заблудший лесной дух', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102033, 6, 0, 1, 'Обучает призывать фамильяра: Заблудший лесной дух. +2% духа; -1% скорости передвижения', 4),
(110034, 15, 2, 'Клетка с: Корешок', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102034, 6, 0, 1, 'Обучает призывать фамильяра: Корешок. +3 сопротивления всем школам магии', 4),
(110035, 15, 2, 'Клетка с: Высохший Корешок', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102035, 6, 0, 1, 'Обучает призывать фамильяра: Высохший Корешок. +3 сопротивления всем школам магии; -1% духа', 4),
(110036, 15, 2, 'Клетка с: Изумрудный дракон', 58861, 3, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102036, 6, 0, 1, 'Обучает призывать фамильяра: Изумрудный дракон. +5% исходящего лечения, +3% восстановления маны', 4),
(110037, 15, 2, 'Клетка с: Детеныш хамелеона', 58861, 3, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102037, 6, 0, 1, 'Обучает призывать фамильяра: Детеныш хамелеона. +5% исходящего лечения, +3% интеллекта', 4),
(110038, 15, 2, 'Клетка с: Древник-Хранитель', 58861, 3, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102038, 6, 0, 1, 'Обучает призывать фамильяра: Древник-Хранитель. +5% исходящего лечения, +5 сопротивления природе', 4),
(110039, 15, 2, 'Клетка с: Дух Древа', 58861, 4, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102039, 6, 0, 1, 'Обучает призывать фамильяра: Дух Древа. +10% исходящего лечения, +5% духа, +5% интеллекта; -10 сопротивления тени, -5% выносливости', 4);

INSERT INTO item_template_locale (ID, locale, Name, Description) VALUES
(110030, 'ruRU', 'Клетка с: Светлячок', 'Обучает призывать фамильяра: Светлячок. +2% исходящего лечения'),
(110031, 'ruRU', 'Клетка с: Угасший Светлячок', 'Обучает призывать фамильяра: Угасший Светлячок. +2% исходящего лечения; -1% интеллекта'),
(110032, 'ruRU', 'Клетка с: Лесной дух', 'Обучает призывать фамильяра: Лесной дух. +2% духа'),
(110033, 'ruRU', 'Клетка с: Заблудший лесной дух', 'Обучает призывать фамильяра: Заблудший лесной дух. +2% духа; -1% скорости передвижения'),
(110034, 'ruRU', 'Клетка с: Корешок', 'Обучает призывать фамильяра: Корешок. +3 сопротивления всем школам магии'),
(110035, 'ruRU', 'Клетка с: Высохший Корешок', 'Обучает призывать фамильяра: Высохший Корешок. +3 сопротивления всем школам магии; -1% духа'),
(110036, 'ruRU', 'Клетка с: Изумрудный дракон', 'Обучает призывать фамильяра: Изумрудный дракон. +5% исходящего лечения, +3% восстановления маны'),
(110037, 'ruRU', 'Клетка с: Детеныш хамелеона', 'Обучает призывать фамильяра: Детеныш хамелеона. +5% исходящего лечения, +3% интеллекта'),
(110038, 'ruRU', 'Клетка с: Древник-Хранитель', 'Обучает призывать фамильяра: Древник-Хранитель. +5% исходящего лечения, +5 сопротивления природе'),
(110039, 'ruRU', 'Клетка с: Дух Древа', 'Обучает призывать фамильяра: Дух Древа. +10% исходящего лечения, +5% духа, +5% интеллекта; -10 сопротивления тени, -5% выносливости');