-- ============================================================================
-- Nemesis Familiar Gacha — family 5 (Светлый / light)
-- AUTO-GENERATED by scripts/familiar-gen-sql.ps1 from 05_light.json
-- Do not hand-edit: change the JSON and regenerate.
--
-- amount = EffectBasePoints + 1 (DieSides=1). buff=0x80000000,
-- debuff=0x84000000 (NO_AURA_CANCEL | AURA_IS_DEBUFF). See generator header.
-- ============================================================================

-- STEP 1: spell_dbc — summon spells
DELETE FROM spell_dbc WHERE ID IN (102040, 102041, 102042, 102043, 102044, 102045, 102046, 102047, 102048, 102049);
REPLACE INTO spell_dbc (ID, Attributes, CastingTimeIndex, DurationIndex, RangeIndex, EquippedItemClass, Effect_1, EffectMiscValue_1, EffectMiscValueB_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS) VALUES
(102040, 262416, 1, 21, 1, -1, 28, 191040, 41, 32, 1, 3052, 'Summon Familiar: Светлокрылка'),
(102041, 262416, 1, 21, 1, -1, 28, 191041, 41, 32, 1, 3052, 'Summon Familiar: Тусклокрылка'),
(102042, 262416, 1, 21, 1, -1, 28, 191042, 41, 32, 1, 3278, 'Summon Familiar: Святой Мотылёк'),
(102043, 262416, 1, 21, 1, -1, 28, 191043, 41, 32, 1, 3278, 'Summon Familiar: Раненый Мотылёк'),
(102044, 262416, 1, 21, 1, -1, 28, 191044, 41, 32, 1, 3744, 'Summon Familiar: Святой Помощник'),
(102045, 262416, 1, 21, 1, -1, 28, 191045, 41, 32, 1, 3744, 'Summon Familiar: Малый Святой Помощник'),
(102046, 262416, 1, 21, 1, -1, 28, 191046, 41, 32, 1, 540, 'Summon Familiar: Осветляющий'),
(102047, 262416, 1, 21, 1, -1, 28, 191047, 41, 32, 1, 1801, 'Summon Familiar: Светлый Защитник'),
(102048, 262416, 1, 21, 1, -1, 28, 191048, 41, 32, 1, 540, 'Summon Familiar: Светлый Победитель'),
(102049, 262416, 1, 21, 1, -1, 28, 191049, 41, 32, 1, 2176, 'Summon Familiar: Хранитель Света');

-- STEP 2: spell_dbc — positive owner-auras (103xxx, buff bar)
DELETE FROM spell_dbc WHERE ID IN (103040, 103041, 103042, 103043, 103044, 103045, 103046, 103047, 103048, 103049);
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103040, 2147483648, 21, 101, 1, -1, 6, 79, 1, 1, 2, 1, 1, 3052, 'Familiar Aura: Светлокрылка', '+2% урона светом');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103041, 2147483648, 21, 101, 1, -1, 6, 79, 1, 1, 2, 1, 1, 3052, 'Familiar Aura: Тусклокрылка', '+2% урона светом');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103042, 2147483648, 21, 101, 1, -1, 6, 118, 1, 1, 0, 1, 1, 3278, 'Familiar Aura: Святой Мотылёк', '+2% получаемого лечения');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103043, 2147483648, 21, 101, 1, -1, 6, 118, 1, 1, 0, 1, 1, 3278, 'Familiar Aura: Раненый Мотылёк', '+2% получаемого лечения');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103044, 2147483648, 21, 101, 1, -1, 6, 136, 1, 1, 0, 1, 1, 3744, 'Familiar Aura: Святой Помощник', '+2% исходящего лечения');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103045, 2147483648, 21, 101, 1, -1, 6, 136, 1, 1, 0, 1, 1, 3744, 'Familiar Aura: Малый Святой Помощник', '+2% исходящего лечения');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103046, 2147483648, 21, 101, 1, -1, 6, 79, 4, 1, 2, 1, 6, 137, 2, 1, 2, 1, 1, 540, 'Familiar Aura: Осветляющий', '+5% урона светом, +3% выносливости');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103047, 2147483648, 21, 101, 1, -1, 6, 79, 4, 1, 2, 1, 6, 137, 2, 1, 3, 1, 1, 1801, 'Familiar Aura: Светлый Защитник', '+5% урона светом, +3% интеллекта');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103048, 2147483648, 21, 101, 1, -1, 6, 79, 4, 1, 2, 1, 6, 22, 4, 1, 32, 1, 1, 540, 'Familiar Aura: Светлый Победитель', '+5% урона светом, +5 сопротивления тени');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, Effect_3, EffectAura_3, EffectBasePoints_3, EffectDieSides_3, EffectMiscValue_3, ImplicitTargetA_3, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103049, 2147483648, 21, 101, 1, -1, 6, 79, 9, 1, 2, 1, 6, 137, 4, 1, 2, 1, 6, 137, 4, 1, 0, 1, 1, 2176, 'Familiar Aura: Хранитель Света', '+10% урона светом, +5% выносливости, +5% силы');

-- STEP 3: spell_dbc — negative owner-auras (104xxx, debuff bar)
DELETE FROM spell_dbc WHERE ID IN (104041, 104043, 104045, 104049);
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(104041, 2214592512, 21, 101, 1, -1, 6, 137, -2, 1, 3, 1, 1, 3052, 'Familiar Debuff: Тусклокрылка', '-1% интеллекта');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(104043, 2214592512, 21, 101, 1, -1, 6, 31, -2, 1, 0, 1, 1, 3278, 'Familiar Debuff: Раненый Мотылёк', '-1% скорости передвижения');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(104045, 2214592512, 21, 101, 1, -1, 6, 137, -2, 1, 4, 1, 1, 3744, 'Familiar Debuff: Малый Святой Помощник', '-1% духа');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(104049, 2214592512, 21, 101, 1, -1, 6, 22, -11, 1, 32, 1, 6, 137, -6, 1, 3, 1, 1, 2176, 'Familiar Debuff: Хранитель Света', '-10 сопротивления тени, -5% интеллекта');

-- STEP 4: creature_template + _model + _locale
DELETE FROM creature_template_locale WHERE entry IN (191040, 191041, 191042, 191043, 191044, 191045, 191046, 191047, 191048, 191049);
DELETE FROM creature_template_model  WHERE CreatureID IN (191040, 191041, 191042, 191043, 191044, 191045, 191046, 191047, 191048, 191049);
DELETE FROM creature_template        WHERE entry IN (191040, 191041, 191042, 191043, 191044, 191045, 191046, 191047, 191048, 191049);

REPLACE INTO creature_template (entry, name, subname, minlevel, maxlevel, faction, unit_class, type, family, npcflag, AIName) VALUES
(191040, 'Светлокрылка', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191041, 'Тусклокрылка', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191042, 'Святой Мотылёк', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191043, 'Раненый Мотылёк', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191044, 'Святой Помощник', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191045, 'Малый Святой Помощник', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191046, 'Осветляющий', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191047, 'Светлый Защитник', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191048, 'Светлый Победитель', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191049, 'Хранитель Света', '', 1, 1, 35, 1, 7, 0, 0, '');

INSERT INTO creature_template_model (CreatureID, Idx, CreatureDisplayID, DisplayScale, Probability, VerifiedBuild) VALUES
(191040, 0, 28215, 1.0, 1, 0),
(191041, 0, 28214, 1.0, 1, 0),
(191042, 0, 19999, 1.0, 1, 0),
(191043, 0, 19999, 1.0, 1, 0),
(191044, 0, 28946, 1.0, 1, 0),
(191045, 0, 28946, 1.0, 1, 0),
(191046, 0, 65046, 0.1, 1, 0),
(191047, 0, 65047, 0.4, 1, 0),
(191048, 0, 65048, 0.1, 1, 0),
(191049, 0, 25900, 1.0, 1, 0);

INSERT INTO creature_template_locale (entry, locale, Name, Title) VALUES
(191040, 'ruRU', 'Светлокрылка', ''),
(191041, 'ruRU', 'Тусклокрылка', ''),
(191042, 'ruRU', 'Святой Мотылёк', ''),
(191043, 'ruRU', 'Раненый Мотылёк', ''),
(191044, 'ruRU', 'Святой Помощник', ''),
(191045, 'ruRU', 'Малый Святой Помощник', ''),
(191046, 'ruRU', 'Осветляющий', ''),
(191047, 'ruRU', 'Светлый Защитник', ''),
(191048, 'ruRU', 'Светлый Победитель', ''),
(191049, 'ruRU', 'Хранитель Света', '');

-- muted-ambient custom displays (need rows in patched CreatureDisplayInfo.dbc, server+client)
DELETE FROM creature_model_info WHERE DisplayID IN (65046, 65047, 65048);
INSERT INTO creature_model_info (DisplayID, BoundingRadius, CombatReach, Gender, DisplayID_Other_Gender)
SELECT 65046, BoundingRadius, CombatReach, Gender, 0 FROM creature_model_info WHERE DisplayID = 22981;
INSERT INTO creature_model_info (DisplayID, BoundingRadius, CombatReach, Gender, DisplayID_Other_Gender)
SELECT 65047, BoundingRadius, CombatReach, Gender, 0 FROM creature_model_info WHERE DisplayID = 17072;
INSERT INTO creature_model_info (DisplayID, BoundingRadius, CombatReach, Gender, DisplayID_Other_Gender)
SELECT 65048, BoundingRadius, CombatReach, Gender, 0 FROM creature_model_info WHERE DisplayID = 18135;

-- STEP 5: item_template (scrolls) + _locale
DELETE FROM item_template_locale WHERE ID IN (110040, 110041, 110042, 110043, 110044, 110045, 110046, 110047, 110048, 110049) AND locale = 'ruRU';
DELETE FROM item_template        WHERE entry IN (110040, 110041, 110042, 110043, 110044, 110045, 110046, 110047, 110048, 110049);

REPLACE INTO item_template (entry, class, subclass, name, displayid, Quality, Flags, BuyPrice, SellPrice, InventoryType, AllowableClass, ItemLevel, RequiredLevel, MaxCount, stackable, spellid_1, spelltrigger_1, spellcharges_1, spellid_2, spelltrigger_2, spellcharges_2, bonding, description, Material) VALUES
(110040, 15, 2, 'Клетка с: Светлокрылка', 20629, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102040, 6, 0, 1, 'Обучает призывать фамильяра: Светлокрылка. +2% урона светом', 4),
(110041, 15, 2, 'Клетка с: Тусклокрылка', 20629, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102041, 6, 0, 1, 'Обучает призывать фамильяра: Тусклокрылка. +2% урона светом; -1% интеллекта', 4),
(110042, 15, 2, 'Клетка с: Святой Мотылёк', 20629, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102042, 6, 0, 1, 'Обучает призывать фамильяра: Святой Мотылёк. +2% получаемого лечения', 4),
(110043, 15, 2, 'Клетка с: Раненый Мотылёк', 20629, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102043, 6, 0, 1, 'Обучает призывать фамильяра: Раненый Мотылёк. +2% получаемого лечения; -1% скорости передвижения', 4),
(110044, 15, 2, 'Клетка с: Святой Помощник', 20629, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102044, 6, 0, 1, 'Обучает призывать фамильяра: Святой Помощник. +2% исходящего лечения', 4),
(110045, 15, 2, 'Клетка с: Малый Святой Помощник', 20629, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102045, 6, 0, 1, 'Обучает призывать фамильяра: Малый Святой Помощник. +2% исходящего лечения; -1% духа', 4),
(110046, 15, 2, 'Клетка с: Осветляющий', 20629, 3, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102046, 6, 0, 1, 'Обучает призывать фамильяра: Осветляющий. +5% урона светом, +3% выносливости', 4),
(110047, 15, 2, 'Клетка с: Светлый Защитник', 20629, 3, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102047, 6, 0, 1, 'Обучает призывать фамильяра: Светлый Защитник. +5% урона светом, +3% интеллекта', 4),
(110048, 15, 2, 'Клетка с: Светлый Победитель', 20629, 3, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102048, 6, 0, 1, 'Обучает призывать фамильяра: Светлый Победитель. +5% урона светом, +5 сопротивления тени', 4),
(110049, 15, 2, 'Клетка с: Хранитель Света', 20629, 4, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102049, 6, 0, 1, 'Обучает призывать фамильяра: Хранитель Света. +10% урона светом, +5% выносливости, +5% силы; -10 сопротивления тени, -5% интеллекта', 4);

INSERT INTO item_template_locale (ID, locale, Name, Description) VALUES
(110040, 'ruRU', 'Клетка с: Светлокрылка', 'Обучает призывать фамильяра: Светлокрылка. +2% урона светом'),
(110041, 'ruRU', 'Клетка с: Тусклокрылка', 'Обучает призывать фамильяра: Тусклокрылка. +2% урона светом; -1% интеллекта'),
(110042, 'ruRU', 'Клетка с: Святой Мотылёк', 'Обучает призывать фамильяра: Святой Мотылёк. +2% получаемого лечения'),
(110043, 'ruRU', 'Клетка с: Раненый Мотылёк', 'Обучает призывать фамильяра: Раненый Мотылёк. +2% получаемого лечения; -1% скорости передвижения'),
(110044, 'ruRU', 'Клетка с: Святой Помощник', 'Обучает призывать фамильяра: Святой Помощник. +2% исходящего лечения'),
(110045, 'ruRU', 'Клетка с: Малый Святой Помощник', 'Обучает призывать фамильяра: Малый Святой Помощник. +2% исходящего лечения; -1% духа'),
(110046, 'ruRU', 'Клетка с: Осветляющий', 'Обучает призывать фамильяра: Осветляющий. +5% урона светом, +3% выносливости'),
(110047, 'ruRU', 'Клетка с: Светлый Защитник', 'Обучает призывать фамильяра: Светлый Защитник. +5% урона светом, +3% интеллекта'),
(110048, 'ruRU', 'Клетка с: Светлый Победитель', 'Обучает призывать фамильяра: Светлый Победитель. +5% урона светом, +5 сопротивления тени'),
(110049, 'ruRU', 'Клетка с: Хранитель Света', 'Обучает призывать фамильяра: Хранитель Света. +10% урона светом, +5% выносливости, +5% силы; -10 сопротивления тени, -5% интеллекта');