-- ============================================================================
-- Nemesis Familiar Gacha — family 10 (Общий / spirit)
-- AUTO-GENERATED by scripts/familiar-gen-sql.ps1 from 10_spirit.json
-- Do not hand-edit: change the JSON and regenerate.
--
-- amount = EffectBasePoints + 1 (DieSides=1). buff=0x80000000,
-- debuff=0x84000000 (NO_AURA_CANCEL | AURA_IS_DEBUFF). See generator header.
-- ============================================================================

-- STEP 1: spell_dbc — summon spells
DELETE FROM spell_dbc WHERE ID IN (102090, 102091, 102092, 102093, 102094, 102095, 102096, 102097, 102098, 102099);
REPLACE INTO spell_dbc (ID, Attributes, CastingTimeIndex, DurationIndex, RangeIndex, EquippedItemClass, Effect_1, EffectMiscValue_1, EffectMiscValueB_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS) VALUES
(102090, 262416, 1, 21, 1, -1, 28, 191090, 41, 32, 1, 2224, 'Summon Familiar: Сквернокот'),
(102091, 262416, 1, 21, 1, -1, 28, 191091, 41, 32, 1, 2224, 'Summon Familiar: Хромой Сквернокот'),
(102092, 262416, 1, 21, 1, -1, 28, 191092, 41, 32, 1, 3058, 'Summon Familiar: Хлебная Жаба'),
(102093, 262416, 1, 21, 1, -1, 28, 191093, 41, 32, 1, 3058, 'Summon Familiar: Подмокшая Хлебная Жаба'),
(102094, 262416, 1, 21, 1, -1, 28, 191094, 41, 32, 1, 2804, 'Summon Familiar: Тотемный Дух'),
(102095, 262416, 1, 21, 1, -1, 28, 191095, 41, 32, 1, 2804, 'Summon Familiar: Треснутый Тотемный Дух'),
(102096, 262416, 1, 21, 1, -1, 28, 191096, 41, 32, 1, 3910, 'Summon Familiar: Живое Яйцо'),
(102097, 262416, 1, 21, 1, -1, 28, 191097, 41, 32, 1, 2316, 'Summon Familiar: Милый Урчаль'),
(102098, 262416, 1, 21, 1, -1, 28, 191098, 41, 32, 1, 1541, 'Summon Familiar: Слайм'),
(102099, 262416, 1, 21, 1, -1, 28, 191099, 41, 32, 1, 2717, 'Summon Familiar: Везунчик');

-- STEP 2: spell_dbc — positive owner-auras (103xxx, buff bar)
DELETE FROM spell_dbc WHERE ID IN (103090, 103091, 103092, 103093, 103094, 103095, 103096, 103097, 103098, 103099);
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103090, 2147483648, 21, 101, 1, -1, 6, 137, 0, 1, -1, 1, 1, 2224, 'Familiar Aura: Сквернокот', '+1% всех характеристик');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103091, 2147483648, 21, 101, 1, -1, 6, 137, 0, 1, -1, 1, 1, 2224, 'Familiar Aura: Хромой Сквернокот', '+1% всех характеристик');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103092, 2147483648, 21, 101, 1, -1, 6, 200, 1, 1, 0, 1, 1, 3058, 'Familiar Aura: Хлебная Жаба', '+2% опыта');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103093, 2147483648, 21, 101, 1, -1, 6, 200, 1, 1, 0, 1, 1, 3058, 'Familiar Aura: Подмокшая Хлебная Жаба', '+2% опыта');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103094, 2147483648, 21, 101, 1, -1, 6, 281, 2, 1, 0, 1, 1, 2804, 'Familiar Aura: Тотемный Дух', '+3% прироста чести');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103095, 2147483648, 21, 101, 1, -1, 6, 281, 2, 1, 0, 1, 1, 2804, 'Familiar Aura: Треснутый Тотемный Дух', '+3% прироста чести');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103096, 2147483648, 21, 101, 1, -1, 6, 137, 1, 1, -1, 1, 6, 281, 2, 1, 0, 1, 1, 3910, 'Familiar Aura: Живое Яйцо', '+2% всех характеристик, +3% прироста чести');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103097, 2147483648, 21, 101, 1, -1, 6, 200, 4, 1, 0, 1, 6, 31, 4, 1, 0, 1, 1, 2316, 'Familiar Aura: Милый Урчаль', '+5% опыта, +5% скорости передвижения');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103098, 2147483648, 21, 101, 1, -1, 6, 200, 4, 1, 0, 1, 6, 156, 4, 1, 0, 1, 1, 1541, 'Familiar Aura: Слайм', '+5% опыта, +5% прироста репутации');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, Effect_3, EffectAura_3, EffectBasePoints_3, EffectDieSides_3, EffectMiscValue_3, ImplicitTargetA_3, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103099, 2147483648, 21, 101, 1, -1, 6, 200, 9, 1, 0, 1, 6, 281, 9, 1, 0, 1, 6, 156, 9, 1, 0, 1, 1, 2717, 'Familiar Aura: Везунчик', '+10% опыта, +10% прироста чести, +10% прироста репутации');

-- STEP 3: spell_dbc — negative owner-auras (104xxx, debuff bar)
DELETE FROM spell_dbc WHERE ID IN (104091, 104093, 104095, 104099);
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(104091, 2214592512, 21, 101, 1, -1, 6, 137, -2, 1, 2, 1, 1, 2224, 'Familiar Debuff: Хромой Сквернокот', '-1% выносливости');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(104093, 2214592512, 21, 101, 1, -1, 6, 137, -2, 1, -1, 1, 1, 3058, 'Familiar Debuff: Подмокшая Хлебная Жаба', '-1% всех характеристик');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(104095, 2214592512, 21, 101, 1, -1, 6, 137, -2, 1, 2, 1, 1, 2804, 'Familiar Debuff: Треснутый Тотемный Дух', '-1% выносливости');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(104099, 2214592512, 21, 101, 1, -1, 6, 137, -6, 1, -1, 1, 1, 2717, 'Familiar Debuff: Везунчик', '-5% всех характеристик');

-- STEP 4: creature_template + _model + _locale
DELETE FROM creature_template_locale WHERE entry IN (191090, 191091, 191092, 191093, 191094, 191095, 191096, 191097, 191098, 191099);
DELETE FROM creature_template_model  WHERE CreatureID IN (191090, 191091, 191092, 191093, 191094, 191095, 191096, 191097, 191098, 191099);
DELETE FROM creature_template        WHERE entry IN (191090, 191091, 191092, 191093, 191094, 191095, 191096, 191097, 191098, 191099);

REPLACE INTO creature_template (entry, name, subname, minlevel, maxlevel, faction, unit_class, type, family, npcflag, AIName) VALUES
(191090, 'Сквернокот', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191091, 'Хромой Сквернокот', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191092, 'Хлебная Жаба', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191093, 'Подмокшая Хлебная Жаба', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191094, 'Тотемный Дух', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191095, 'Треснутый Тотемный Дух', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191096, 'Живое Яйцо', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191097, 'Милый Урчаль', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191098, 'Слайм', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191099, 'Везунчик', '', 1, 1, 35, 1, 7, 0, 0, '');

INSERT INTO creature_template_model (CreatureID, Idx, CreatureDisplayID, DisplayScale, Probability, VerifiedBuild) VALUES
(191090, 0, 9209, 1.0, 1, 0),
(191091, 0, 9209, 1.0, 1, 0),
(191092, 0, 22459, 1.0, 1, 0),
(191093, 0, 22459, 1.0, 1, 0),
(191094, 0, 29189, 1.0, 1, 0),
(191095, 0, 29189, 1.0, 1, 0),
(191096, 0, 21382, 1.0, 1, 0),
(191097, 0, 15398, 1.0, 1, 0),
(191098, 0, 65098, 1.0, 1, 0),
(191099, 0, 21304, 1.0, 1, 0);

INSERT INTO creature_template_locale (entry, locale, Name, Title) VALUES
(191090, 'ruRU', 'Сквернокот', ''),
(191091, 'ruRU', 'Хромой Сквернокот', ''),
(191092, 'ruRU', 'Хлебная Жаба', ''),
(191093, 'ruRU', 'Подмокшая Хлебная Жаба', ''),
(191094, 'ruRU', 'Тотемный Дух', ''),
(191095, 'ruRU', 'Треснутый Тотемный Дух', ''),
(191096, 'ruRU', 'Живое Яйцо', ''),
(191097, 'ruRU', 'Милый Урчаль', ''),
(191098, 'ruRU', 'Слайм', ''),
(191099, 'ruRU', 'Везунчик', '');

-- muted-ambient custom displays (need rows in patched CreatureDisplayInfo.dbc, server+client)
DELETE FROM creature_model_info WHERE DisplayID IN (65098);
INSERT INTO creature_model_info (DisplayID, BoundingRadius, CombatReach, Gender, DisplayID_Other_Gender)
SELECT 65098, BoundingRadius, CombatReach, Gender, 0 FROM creature_model_info WHERE DisplayID = 31073;

-- STEP 5: item_template (scrolls) + _locale
DELETE FROM item_template_locale WHERE ID IN (110090, 110091, 110092, 110093, 110094, 110095, 110096, 110097, 110098, 110099) AND locale = 'ruRU';
DELETE FROM item_template        WHERE entry IN (110090, 110091, 110092, 110093, 110094, 110095, 110096, 110097, 110098, 110099);

REPLACE INTO item_template (entry, class, subclass, name, displayid, Quality, Flags, BuyPrice, SellPrice, InventoryType, AllowableClass, ItemLevel, RequiredLevel, MaxCount, stackable, spellid_1, spelltrigger_1, spellcharges_1, spellid_2, spelltrigger_2, spellcharges_2, bonding, description, Material) VALUES
(110090, 15, 2, 'Клетка с: Сквернокот', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102090, 6, 0, 1, 'Обучает призывать фамильяра: Сквернокот. +1% всех характеристик', 4),
(110091, 15, 2, 'Клетка с: Хромой Сквернокот', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102091, 6, 0, 1, 'Обучает призывать фамильяра: Хромой Сквернокот. +1% всех характеристик; -1% выносливости', 4),
(110092, 15, 2, 'Клетка с: Хлебная Жаба', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102092, 6, 0, 1, 'Обучает призывать фамильяра: Хлебная Жаба. +2% опыта', 4),
(110093, 15, 2, 'Клетка с: Подмокшая Хлебная Жаба', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102093, 6, 0, 1, 'Обучает призывать фамильяра: Подмокшая Хлебная Жаба. +2% опыта; -1% всех характеристик', 4),
(110094, 15, 2, 'Клетка с: Тотемный Дух', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102094, 6, 0, 1, 'Обучает призывать фамильяра: Тотемный Дух. +3% прироста чести', 4),
(110095, 15, 2, 'Клетка с: Треснутый Тотемный Дух', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102095, 6, 0, 1, 'Обучает призывать фамильяра: Треснутый Тотемный Дух. +3% прироста чести; -1% выносливости', 4),
(110096, 15, 2, 'Клетка с: Живое Яйцо', 58861, 3, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102096, 6, 0, 1, 'Обучает призывать фамильяра: Живое Яйцо. +2% всех характеристик, +3% прироста чести', 4),
(110097, 15, 2, 'Клетка с: Милый Урчаль', 58861, 3, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102097, 6, 0, 1, 'Обучает призывать фамильяра: Милый Урчаль. +5% опыта, +5% скорости передвижения', 4),
(110098, 15, 2, 'Клетка с: Слайм', 58861, 3, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102098, 6, 0, 1, 'Обучает призывать фамильяра: Слайм. +5% опыта, +5% прироста репутации', 4),
(110099, 15, 2, 'Клетка с: Везунчик', 58861, 4, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102099, 6, 0, 1, 'Обучает призывать фамильяра: Везунчик. +10% опыта, +10% прироста чести, +10% прироста репутации; -5% всех характеристик', 4);

INSERT INTO item_template_locale (ID, locale, Name, Description) VALUES
(110090, 'ruRU', 'Клетка с: Сквернокот', 'Обучает призывать фамильяра: Сквернокот. +1% всех характеристик'),
(110091, 'ruRU', 'Клетка с: Хромой Сквернокот', 'Обучает призывать фамильяра: Хромой Сквернокот. +1% всех характеристик; -1% выносливости'),
(110092, 'ruRU', 'Клетка с: Хлебная Жаба', 'Обучает призывать фамильяра: Хлебная Жаба. +2% опыта'),
(110093, 'ruRU', 'Клетка с: Подмокшая Хлебная Жаба', 'Обучает призывать фамильяра: Подмокшая Хлебная Жаба. +2% опыта; -1% всех характеристик'),
(110094, 'ruRU', 'Клетка с: Тотемный Дух', 'Обучает призывать фамильяра: Тотемный Дух. +3% прироста чести'),
(110095, 'ruRU', 'Клетка с: Треснутый Тотемный Дух', 'Обучает призывать фамильяра: Треснутый Тотемный Дух. +3% прироста чести; -1% выносливости'),
(110096, 'ruRU', 'Клетка с: Живое Яйцо', 'Обучает призывать фамильяра: Живое Яйцо. +2% всех характеристик, +3% прироста чести'),
(110097, 'ruRU', 'Клетка с: Милый Урчаль', 'Обучает призывать фамильяра: Милый Урчаль. +5% опыта, +5% скорости передвижения'),
(110098, 'ruRU', 'Клетка с: Слайм', 'Обучает призывать фамильяра: Слайм. +5% опыта, +5% прироста репутации'),
(110099, 'ruRU', 'Клетка с: Везунчик', 'Обучает призывать фамильяра: Везунчик. +10% опыта, +10% прироста чести, +10% прироста репутации; -5% всех характеристик');