-- ============================================================================
-- Nemesis Familiar Gacha — family 2 (Огненный / fire)
-- AUTO-GENERATED by scripts/familiar-gen-sql.ps1 from 02_fire.json
-- Do not hand-edit: change the JSON and regenerate.
--
-- amount = EffectBasePoints + 1 (DieSides=1). buff=0x80000000,
-- debuff=0x84000000 (NO_AURA_CANCEL | AURA_IS_DEBUFF). See generator header.
-- ============================================================================

-- STEP 1: spell_dbc — summon spells
DELETE FROM spell_dbc WHERE ID IN (102010, 102011, 102012, 102013, 102014, 102015, 102016, 102017, 102018, 102019);
REPLACE INTO spell_dbc (ID, Attributes, CastingTimeIndex, DurationIndex, RangeIndex, EquippedItemClass, Effect_1, EffectMiscValue_1, EffectMiscValueB_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS) VALUES
(102010, 262416, 1, 21, 1, -1, 28, 191010, 41, 32, 1, 876, 'Summon Familiar: Бес-Поджигатель'),
(102011, 262416, 1, 21, 1, -1, 28, 191011, 41, 32, 1, 876, 'Summon Familiar: Хромой Бесёныш'),
(102012, 262416, 1, 21, 1, -1, 28, 191012, 41, 32, 1, 2019, 'Summon Familiar: Уголёк'),
(102013, 262416, 1, 21, 1, -1, 28, 191013, 41, 32, 1, 2019, 'Summon Familiar: Тлеющий Уголёк'),
(102014, 262416, 1, 21, 1, -1, 28, 191014, 41, 32, 1, 1548, 'Summon Familiar: Огнекрыл-Малыш'),
(102015, 262416, 1, 21, 1, -1, 28, 191015, 41, 32, 1, 1548, 'Summon Familiar: Опалённый Огнекрыл'),
(102016, 262416, 1, 21, 1, -1, 28, 191016, 41, 32, 1, 3874, 'Summon Familiar: Пламенный Жнец'),
(102017, 262416, 1, 21, 1, -1, 28, 191017, 41, 32, 1, 2787, 'Summon Familiar: Фоукс'),
(102018, 262416, 1, 21, 1, -1, 28, 191018, 41, 32, 1, 4062, 'Summon Familiar: Демон-Поджигатель'),
(102019, 262416, 1, 21, 1, -1, 28, 191019, 41, 32, 1, 3819, 'Summon Familiar: Аватар Огня');

-- STEP 2: spell_dbc — positive owner-auras (103xxx, buff bar)
DELETE FROM spell_dbc WHERE ID IN (103010, 103011, 103012, 103013, 103014, 103015, 103016, 103017, 103018, 103019);
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103010, 2147483648, 21, 101, 1, -1, 6, 79, 1, 1, 4, 1, 1, 876, 'Familiar Aura: Бес-Поджигатель', '+2% урона огнём');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103011, 2147483648, 21, 101, 1, -1, 6, 79, 1, 1, 4, 1, 1, 876, 'Familiar Aura: Хромой Бесёныш', '+2% урона огнём');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103012, 2147483648, 21, 101, 1, -1, 6, 57, 0, 1, 0, 1, 1, 2019, 'Familiar Aura: Уголёк', '+1% шанса критического удара заклинаний');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103013, 2147483648, 21, 101, 1, -1, 6, 57, 0, 1, 0, 1, 1, 2019, 'Familiar Aura: Тлеющий Уголёк', '+1% шанса критического удара заклинаний');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103014, 2147483648, 21, 101, 1, -1, 6, 137, 0, 1, 3, 1, 1, 1548, 'Familiar Aura: Огнекрыл-Малыш', '+1% интеллекта');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103015, 2147483648, 21, 101, 1, -1, 6, 137, 0, 1, 3, 1, 1, 1548, 'Familiar Aura: Опалённый Огнекрыл', '+1% интеллекта');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103016, 2147483648, 21, 101, 1, -1, 6, 79, 4, 1, 4, 1, 6, 57, 2, 1, 0, 1, 1, 3874, 'Familiar Aura: Пламенный Жнец', '+5% урона огнём, +3% шанса критического удара заклинаний');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103017, 2147483648, 21, 101, 1, -1, 6, 79, 4, 1, 4, 1, 6, 22, 4, 1, 4, 1, 1, 2787, 'Familiar Aura: Фоукс', '+5% урона огнём, +5 сопротивления огню');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103018, 2147483648, 21, 101, 1, -1, 6, 79, 4, 1, 4, 1, 6, 65, 2, 1, 0, 1, 1, 4062, 'Familiar Aura: Демон-Поджигатель', '+5% урона огнём, +3% скорости накладывания заклинаний');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, Effect_3, EffectAura_3, EffectBasePoints_3, EffectDieSides_3, EffectMiscValue_3, ImplicitTargetA_3, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103019, 2147483648, 21, 101, 1, -1, 6, 79, 9, 1, 4, 1, 6, 57, 4, 1, 0, 1, 6, 137, 4, 1, 3, 1, 1, 3819, 'Familiar Aura: Аватар Огня', '+10% урона огнём, +5% шанса критического удара заклинаний, +5% интеллекта');

-- STEP 3: spell_dbc — negative owner-auras (104xxx, debuff bar)
DELETE FROM spell_dbc WHERE ID IN (104011, 104013, 104015, 104019);
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(104011, 2214592512, 21, 101, 1, -1, 6, 22, -2, 1, 16, 1, 1, 876, 'Familiar Debuff: Хромой Бесёныш', '-1 сопротивления морозу');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(104013, 2214592512, 21, 101, 1, -1, 6, 137, -2, 1, 2, 1, 1, 2019, 'Familiar Debuff: Тлеющий Уголёк', '-1% выносливости');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(104015, 2214592512, 21, 101, 1, -1, 6, 137, -2, 1, 4, 1, 1, 1548, 'Familiar Debuff: Опалённый Огнекрыл', '-1% духа');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(104019, 2214592512, 21, 101, 1, -1, 6, 137, -6, 1, 2, 1, 6, 22, -6, 1, 16, 1, 1, 3819, 'Familiar Debuff: Аватар Огня', '-5% выносливости, -5 сопротивления морозу');

-- STEP 4: creature_template + _model + _locale
DELETE FROM creature_template_locale WHERE entry IN (191010, 191011, 191012, 191013, 191014, 191015, 191016, 191017, 191018, 191019);
DELETE FROM creature_template_model  WHERE CreatureID IN (191010, 191011, 191012, 191013, 191014, 191015, 191016, 191017, 191018, 191019);
DELETE FROM creature_template        WHERE entry IN (191010, 191011, 191012, 191013, 191014, 191015, 191016, 191017, 191018, 191019);

REPLACE INTO creature_template (entry, name, subname, minlevel, maxlevel, faction, unit_class, type, family, npcflag, AIName) VALUES
(191010, 'Бес-Поджигатель', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191011, 'Хромой Бесёныш', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191012, 'Уголёк', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191013, 'Тлеющий Уголёк', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191014, 'Огнекрыл-Малыш', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191015, 'Опалённый Огнекрыл', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191016, 'Пламенный Жнец', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191017, 'Фоукс', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191018, 'Демон-Поджигатель', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191019, 'Аватар Огня', '', 1, 1, 35, 1, 7, 0, 0, '');

INSERT INTO creature_template_model (CreatureID, Idx, CreatureDisplayID, DisplayScale, Probability, VerifiedBuild) VALUES
(191010, 0, 65010, 0.5, 1, 0),
(191011, 0, 65011, 0.5, 1, 0),
(191012, 0, 65012, 0.6, 1, 0),
(191013, 0, 65013, 0.6, 1, 0),
(191014, 0, 6290, 1.0, 1, 0),
(191015, 0, 6290, 1.0, 1, 0),
(191016, 0, 65016, 1.0, 1, 0),
(191017, 0, 23574, 1.0, 1, 0),
(191018, 0, 30462, 1.0, 1, 0),
(191019, 0, 65019, 0.1, 1, 0);

INSERT INTO creature_template_locale (entry, locale, Name, Title) VALUES
(191010, 'ruRU', 'Бес-Поджигатель', ''),
(191011, 'ruRU', 'Хромой Бесёныш', ''),
(191012, 'ruRU', 'Уголёк', ''),
(191013, 'ruRU', 'Тлеющий Уголёк', ''),
(191014, 'ruRU', 'Огнекрыл-Малыш', ''),
(191015, 'ruRU', 'Опалённый Огнекрыл', ''),
(191016, 'ruRU', 'Пламенный Жнец', ''),
(191017, 'ruRU', 'Фоукс', ''),
(191018, 'ruRU', 'Демон-Поджигатель', ''),
(191019, 'ruRU', 'Аватар Огня', '');

-- muted-ambient custom displays (need rows in patched CreatureDisplayInfo.dbc, server+client)
DELETE FROM creature_model_info WHERE DisplayID IN (65010, 65011, 65012, 65013, 65016, 65019);
INSERT INTO creature_model_info (DisplayID, BoundingRadius, CombatReach, Gender, DisplayID_Other_Gender)
SELECT 65010, BoundingRadius, CombatReach, Gender, 0 FROM creature_model_info WHERE DisplayID = 10817;
INSERT INTO creature_model_info (DisplayID, BoundingRadius, CombatReach, Gender, DisplayID_Other_Gender)
SELECT 65011, BoundingRadius, CombatReach, Gender, 0 FROM creature_model_info WHERE DisplayID = 10817;
INSERT INTO creature_model_info (DisplayID, BoundingRadius, CombatReach, Gender, DisplayID_Other_Gender)
SELECT 65012, BoundingRadius, CombatReach, Gender, 0 FROM creature_model_info WHERE DisplayID = 14380;
INSERT INTO creature_model_info (DisplayID, BoundingRadius, CombatReach, Gender, DisplayID_Other_Gender)
SELECT 65013, BoundingRadius, CombatReach, Gender, 0 FROM creature_model_info WHERE DisplayID = 14380;
INSERT INTO creature_model_info (DisplayID, BoundingRadius, CombatReach, Gender, DisplayID_Other_Gender)
SELECT 65016, BoundingRadius, CombatReach, Gender, 0 FROM creature_model_info WHERE DisplayID = 8409;
INSERT INTO creature_model_info (DisplayID, BoundingRadius, CombatReach, Gender, DisplayID_Other_Gender)
SELECT 65019, BoundingRadius, CombatReach, Gender, 0 FROM creature_model_info WHERE DisplayID = 18139;

-- STEP 5: item_template (scrolls) + _locale
DELETE FROM item_template_locale WHERE ID IN (110010, 110011, 110012, 110013, 110014, 110015, 110016, 110017, 110018, 110019) AND locale = 'ruRU';
DELETE FROM item_template        WHERE entry IN (110010, 110011, 110012, 110013, 110014, 110015, 110016, 110017, 110018, 110019);

REPLACE INTO item_template (entry, class, subclass, name, displayid, Quality, Flags, BuyPrice, SellPrice, InventoryType, AllowableClass, ItemLevel, RequiredLevel, MaxCount, stackable, spellid_1, spelltrigger_1, spellcharges_1, spellid_2, spelltrigger_2, spellcharges_2, bonding, description, Material) VALUES
(110010, 15, 2, 'Клетка с: Бес-Поджигатель', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102010, 6, 0, 1, 'Обучает призывать фамильяра: Бес-Поджигатель. +2% урона огнём', 4),
(110011, 15, 2, 'Клетка с: Хромой Бесёныш', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102011, 6, 0, 1, 'Обучает призывать фамильяра: Хромой Бесёныш. +2% урона огнём; -1 сопротивления морозу', 4),
(110012, 15, 2, 'Клетка с: Уголёк', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102012, 6, 0, 1, 'Обучает призывать фамильяра: Уголёк. +1% шанса критического удара заклинаний', 4),
(110013, 15, 2, 'Клетка с: Тлеющий Уголёк', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102013, 6, 0, 1, 'Обучает призывать фамильяра: Тлеющий Уголёк. +1% шанса критического удара заклинаний; -1% выносливости', 4),
(110014, 15, 2, 'Клетка с: Огнекрыл-Малыш', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102014, 6, 0, 1, 'Обучает призывать фамильяра: Огнекрыл-Малыш. +1% интеллекта', 4),
(110015, 15, 2, 'Клетка с: Опалённый Огнекрыл', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102015, 6, 0, 1, 'Обучает призывать фамильяра: Опалённый Огнекрыл. +1% интеллекта; -1% духа', 4),
(110016, 15, 2, 'Клетка с: Пламенный Жнец', 58861, 3, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102016, 6, 0, 1, 'Обучает призывать фамильяра: Пламенный Жнец. +5% урона огнём, +3% шанса критического удара заклинаний', 4),
(110017, 15, 2, 'Клетка с: Фоукс', 58861, 3, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102017, 6, 0, 1, 'Обучает призывать фамильяра: Фоукс. +5% урона огнём, +5 сопротивления огню', 4),
(110018, 15, 2, 'Клетка с: Демон-Поджигатель', 58861, 3, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102018, 6, 0, 1, 'Обучает призывать фамильяра: Демон-Поджигатель. +5% урона огнём, +3% скорости накладывания заклинаний', 4),
(110019, 15, 2, 'Клетка с: Аватар Огня', 58861, 4, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102019, 6, 0, 1, 'Обучает призывать фамильяра: Аватар Огня. +10% урона огнём, +5% шанса критического удара заклинаний, +5% интеллекта; -5% выносливости, -5 сопротивления морозу', 4);

INSERT INTO item_template_locale (ID, locale, Name, Description) VALUES
(110010, 'ruRU', 'Клетка с: Бес-Поджигатель', 'Обучает призывать фамильяра: Бес-Поджигатель. +2% урона огнём'),
(110011, 'ruRU', 'Клетка с: Хромой Бесёныш', 'Обучает призывать фамильяра: Хромой Бесёныш. +2% урона огнём; -1 сопротивления морозу'),
(110012, 'ruRU', 'Клетка с: Уголёк', 'Обучает призывать фамильяра: Уголёк. +1% шанса критического удара заклинаний'),
(110013, 'ruRU', 'Клетка с: Тлеющий Уголёк', 'Обучает призывать фамильяра: Тлеющий Уголёк. +1% шанса критического удара заклинаний; -1% выносливости'),
(110014, 'ruRU', 'Клетка с: Огнекрыл-Малыш', 'Обучает призывать фамильяра: Огнекрыл-Малыш. +1% интеллекта'),
(110015, 'ruRU', 'Клетка с: Опалённый Огнекрыл', 'Обучает призывать фамильяра: Опалённый Огнекрыл. +1% интеллекта; -1% духа'),
(110016, 'ruRU', 'Клетка с: Пламенный Жнец', 'Обучает призывать фамильяра: Пламенный Жнец. +5% урона огнём, +3% шанса критического удара заклинаний'),
(110017, 'ruRU', 'Клетка с: Фоукс', 'Обучает призывать фамильяра: Фоукс. +5% урона огнём, +5 сопротивления огню'),
(110018, 'ruRU', 'Клетка с: Демон-Поджигатель', 'Обучает призывать фамильяра: Демон-Поджигатель. +5% урона огнём, +3% скорости накладывания заклинаний'),
(110019, 'ruRU', 'Клетка с: Аватар Огня', 'Обучает призывать фамильяра: Аватар Огня. +10% урона огнём, +5% шанса критического удара заклинаний, +5% интеллекта; -5% выносливости, -5 сопротивления морозу');