-- ============================================================================
-- Nemesis Familiar Gacha — family 1 (Механический / mech)
-- AUTO-GENERATED by scripts/familiar-gen-sql.ps1 from 01_mech.json
-- Do not hand-edit: change the JSON and regenerate.
--
-- amount = EffectBasePoints + 1 (DieSides=1). buff=0x80000000,
-- debuff=0x84000000 (NO_AURA_CANCEL | AURA_IS_DEBUFF). See generator header.
-- ============================================================================

-- STEP 1: spell_dbc — summon spells
DELETE FROM spell_dbc WHERE ID IN (102000, 102001, 102002, 102003, 102004, 102005, 102006, 102007, 102008, 102009);
REPLACE INTO spell_dbc (ID, Attributes, CastingTimeIndex, DurationIndex, RangeIndex, EquippedItemClass, Effect_1, EffectMiscValue_1, EffectMiscValueB_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS) VALUES
(102000, 262416, 1, 21, 1, -1, 28, 191000, 41, 32, 1, 318, 'Summon Familiar: Механокурица'),
(102001, 262416, 1, 21, 1, -1, 28, 191001, 41, 32, 1, 318, 'Summon Familiar: Ржавая Механокурица'),
(102002, 262416, 1, 21, 1, -1, 28, 191002, 41, 32, 1, 353, 'Summon Familiar: Механобелка'),
(102003, 262416, 1, 21, 1, -1, 28, 191003, 41, 32, 1, 353, 'Summon Familiar: Треснувшая Механобелка'),
(102004, 262416, 1, 21, 1, -1, 28, 191004, 41, 32, 1, 3811, 'Summon Familiar: Бронзовый Щитоносец'),
(102005, 262416, 1, 21, 1, -1, 28, 191005, 41, 32, 1, 3811, 'Summon Familiar: Ржавый Щитоносец'),
(102006, 262416, 1, 21, 1, -1, 28, 191006, 41, 32, 1, 1701, 'Summon Familiar: Ржавый Механодракон'),
(102007, 262416, 1, 21, 1, -1, 28, 191007, 41, 32, 1, 2552, 'Summon Familiar: Железнолоб'),
(102008, 262416, 1, 21, 1, -1, 28, 191008, 41, 32, 1, 3811, 'Summon Familiar: Хрустальный Страж'),
(102009, 262416, 1, 21, 1, -1, 28, 191009, 41, 32, 1, 4375, 'Summon Familiar: Механостраж');

-- STEP 2: spell_dbc — positive owner-auras (103xxx, buff bar)
DELETE FROM spell_dbc WHERE ID IN (103000, 103001, 103002, 103003, 103004, 103005, 103006, 103007, 103008, 103009);
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103000, 2147483648, 21, 101, 1, -1, 6, 101, 0, 1, 1, 1, 1, 318, 'Familiar Aura: Механокурица', '+1% брони');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103001, 2147483648, 21, 101, 1, -1, 6, 101, 0, 1, 1, 1, 1, 318, 'Familiar Aura: Ржавая Механокурица', '+1% брони');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103002, 2147483648, 21, 101, 1, -1, 6, 137, 1, 1, 2, 1, 1, 353, 'Familiar Aura: Механобелка', '+2% выносливости');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103003, 2147483648, 21, 101, 1, -1, 6, 137, 1, 1, 2, 1, 1, 353, 'Familiar Aura: Треснувшая Механобелка', '+2% выносливости');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103004, 2147483648, 21, 101, 1, -1, 6, 51, 1, 1, 0, 1, 1, 3811, 'Familiar Aura: Бронзовый Щитоносец', '+2% блока');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103005, 2147483648, 21, 101, 1, -1, 6, 51, 1, 1, 0, 1, 1, 3811, 'Familiar Aura: Ржавый Щитоносец', '+2% блока');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103006, 2147483648, 21, 101, 1, -1, 6, 101, 2, 1, 1, 1, 6, 137, 2, 1, 2, 1, 1, 1701, 'Familiar Aura: Ржавый Механодракон', '+3% брони, +3% выносливости');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103007, 2147483648, 21, 101, 1, -1, 6, 137, 2, 1, 2, 1, 6, 51, 2, 1, 0, 1, 1, 2552, 'Familiar Aura: Железнолоб', '+3% выносливости, +3% блока');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103008, 2147483648, 21, 101, 1, -1, 6, 101, 2, 1, 1, 1, 6, 22, 2, 1, 126, 1, 1, 3811, 'Familiar Aura: Хрустальный Страж', '+3% брони, +3 сопротивления всем школам магии');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, Effect_3, EffectAura_3, EffectBasePoints_3, EffectDieSides_3, EffectMiscValue_3, ImplicitTargetA_3, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103009, 2147483648, 21, 101, 1, -1, 6, 101, 4, 1, 1, 1, 6, 137, 4, 1, 2, 1, 6, 49, 4, 1, 0, 1, 1, 4375, 'Familiar Aura: Механостраж', '+5% брони, +5% выносливости, +5% уворота');

-- STEP 3: spell_dbc — negative owner-auras (104xxx, debuff bar)
DELETE FROM spell_dbc WHERE ID IN (104001, 104003, 104005, 104009);
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(104001, 2214592512, 21, 101, 1, -1, 6, 31, -2, 1, 0, 1, 1, 318, 'Familiar Debuff: Ржавая Механокурица', '-1% скорости передвижения');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(104003, 2214592512, 21, 101, 1, -1, 6, 137, -2, 1, 4, 1, 1, 353, 'Familiar Debuff: Треснувшая Механобелка', '-1% духа');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(104005, 2214592512, 21, 101, 1, -1, 6, 192, -2, 1, 0, 1, 1, 3811, 'Familiar Debuff: Ржавый Щитоносец', '-1% скорости атаки');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(104009, 2214592512, 21, 101, 1, -1, 6, 166, -11, 1, 0, 1, 6, 290, -6, 1, 0, 1, 1, 4375, 'Familiar Debuff: Механостраж', '-10% силы атаки, -5% шанса критического удара');

-- STEP 4: creature_template + _model + _locale
DELETE FROM creature_template_locale WHERE entry IN (191000, 191001, 191002, 191003, 191004, 191005, 191006, 191007, 191008, 191009);
DELETE FROM creature_template_model  WHERE CreatureID IN (191000, 191001, 191002, 191003, 191004, 191005, 191006, 191007, 191008, 191009);
DELETE FROM creature_template        WHERE entry IN (191000, 191001, 191002, 191003, 191004, 191005, 191006, 191007, 191008, 191009);

REPLACE INTO creature_template (entry, name, subname, minlevel, maxlevel, faction, unit_class, type, family, npcflag, AIName) VALUES
(191000, 'Механокурица', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191001, 'Ржавая Механокурица', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191002, 'Механобелка', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191003, 'Треснувшая Механобелка', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191004, 'Бронзовый Щитоносец', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191005, 'Ржавый Щитоносец', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191006, 'Ржавый Механодракон', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191007, 'Железнолоб', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191008, 'Хрустальный Страж', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191009, 'Механостраж', '', 1, 1, 35, 1, 7, 0, 0, '');

INSERT INTO creature_template_model (CreatureID, Idx, CreatureDisplayID, DisplayScale, Probability, VerifiedBuild) VALUES
(191000, 0, 7920, 1.2, 1, 0),
(191001, 0, 7920, 0.8, 1, 0),
(191002, 0, 7937, 1.0, 1, 0),
(191003, 0, 7937, 1.0, 1, 0),
(191004, 0, 32031, 0.7, 1, 0),
(191005, 0, 32031, 0.8, 1, 0),
(191006, 0, 12489, 1.0, 1, 0),
(191007, 0, 22776, 1.0, 1, 0),
(191008, 0, 65008, 1.0, 1, 0),
(191009, 0, 32670, 1.0, 1, 0);

INSERT INTO creature_template_locale (entry, locale, Name, Title) VALUES
(191000, 'ruRU', 'Механокурица', ''),
(191001, 'ruRU', 'Ржавая Механокурица', ''),
(191002, 'ruRU', 'Механобелка', ''),
(191003, 'ruRU', 'Треснувшая Механобелка', ''),
(191004, 'ruRU', 'Бронзовый Щитоносец', ''),
(191005, 'ruRU', 'Ржавый Щитоносец', ''),
(191006, 'ruRU', 'Ржавый Механодракон', ''),
(191007, 'ruRU', 'Железнолоб', ''),
(191008, 'ruRU', 'Хрустальный Страж', ''),
(191009, 'ruRU', 'Механостраж', '');

-- muted-ambient custom displays (need rows in patched CreatureDisplayInfo.dbc, server+client)
DELETE FROM creature_model_info WHERE DisplayID IN (65008);
INSERT INTO creature_model_info (DisplayID, BoundingRadius, CombatReach, Gender, DisplayID_Other_Gender)
SELECT 65008, BoundingRadius, CombatReach, Gender, 0 FROM creature_model_info WHERE DisplayID = 29060;

-- STEP 5: item_template (scrolls) + _locale
DELETE FROM item_template_locale WHERE ID IN (110000, 110001, 110002, 110003, 110004, 110005, 110006, 110007, 110008, 110009) AND locale = 'ruRU';
DELETE FROM item_template        WHERE entry IN (110000, 110001, 110002, 110003, 110004, 110005, 110006, 110007, 110008, 110009);

REPLACE INTO item_template (entry, class, subclass, name, displayid, Quality, Flags, BuyPrice, SellPrice, InventoryType, AllowableClass, ItemLevel, RequiredLevel, MaxCount, stackable, spellid_1, spelltrigger_1, spellcharges_1, spellid_2, spelltrigger_2, spellcharges_2, bonding, description, Material) VALUES
(110000, 15, 2, 'Клетка с: Механокурица', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102000, 6, 0, 1, 'Обучает призывать фамильяра: Механокурица. +1% брони', 4),
(110001, 15, 2, 'Клетка с: Ржавая Механокурица', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102001, 6, 0, 1, 'Обучает призывать фамильяра: Ржавая Механокурица. +1% брони; -1% скорости передвижения', 4),
(110002, 15, 2, 'Клетка с: Механобелка', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102002, 6, 0, 1, 'Обучает призывать фамильяра: Механобелка. +2% выносливости', 4),
(110003, 15, 2, 'Клетка с: Треснувшая Механобелка', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102003, 6, 0, 1, 'Обучает призывать фамильяра: Треснувшая Механобелка. +2% выносливости; -1% духа', 4),
(110004, 15, 2, 'Клетка с: Бронзовый Щитоносец', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102004, 6, 0, 1, 'Обучает призывать фамильяра: Бронзовый Щитоносец. +2% блока', 4),
(110005, 15, 2, 'Клетка с: Ржавый Щитоносец', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102005, 6, 0, 1, 'Обучает призывать фамильяра: Ржавый Щитоносец. +2% блока; -1% скорости атаки', 4),
(110006, 15, 2, 'Клетка с: Ржавый Механодракон', 58861, 3, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102006, 6, 0, 1, 'Обучает призывать фамильяра: Ржавый Механодракон. +3% брони, +3% выносливости', 4),
(110007, 15, 2, 'Клетка с: Железнолоб', 58861, 3, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102007, 6, 0, 1, 'Обучает призывать фамильяра: Железнолоб. +3% выносливости, +3% блока', 4),
(110008, 15, 2, 'Клетка с: Хрустальный Страж', 58861, 3, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102008, 6, 0, 1, 'Обучает призывать фамильяра: Хрустальный Страж. +3% брони, +3 сопротивления всем школам магии', 4),
(110009, 15, 2, 'Клетка с: Механостраж', 58861, 4, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102009, 6, 0, 1, 'Обучает призывать фамильяра: Механостраж. +5% брони, +5% выносливости, +5% уворота; -10% силы атаки, -5% шанса критического удара', 4);

INSERT INTO item_template_locale (ID, locale, Name, Description) VALUES
(110000, 'ruRU', 'Клетка с: Механокурица', 'Обучает призывать фамильяра: Механокурица. +1% брони'),
(110001, 'ruRU', 'Клетка с: Ржавая Механокурица', 'Обучает призывать фамильяра: Ржавая Механокурица. +1% брони; -1% скорости передвижения'),
(110002, 'ruRU', 'Клетка с: Механобелка', 'Обучает призывать фамильяра: Механобелка. +2% выносливости'),
(110003, 'ruRU', 'Клетка с: Треснувшая Механобелка', 'Обучает призывать фамильяра: Треснувшая Механобелка. +2% выносливости; -1% духа'),
(110004, 'ruRU', 'Клетка с: Бронзовый Щитоносец', 'Обучает призывать фамильяра: Бронзовый Щитоносец. +2% блока'),
(110005, 'ruRU', 'Клетка с: Ржавый Щитоносец', 'Обучает призывать фамильяра: Ржавый Щитоносец. +2% блока; -1% скорости атаки'),
(110006, 'ruRU', 'Клетка с: Ржавый Механодракон', 'Обучает призывать фамильяра: Ржавый Механодракон. +3% брони, +3% выносливости'),
(110007, 'ruRU', 'Клетка с: Железнолоб', 'Обучает призывать фамильяра: Железнолоб. +3% выносливости, +3% блока'),
(110008, 'ruRU', 'Клетка с: Хрустальный Страж', 'Обучает призывать фамильяра: Хрустальный Страж. +3% брони, +3 сопротивления всем школам магии'),
(110009, 'ruRU', 'Клетка с: Механостраж', 'Обучает призывать фамильяра: Механостраж. +5% брони, +5% выносливости, +5% уворота; -10% силы атаки, -5% шанса критического удара');