-- ============================================================================
-- Nemesis Familiar Gacha — family 9 (Звериный / beast)
-- AUTO-GENERATED by scripts/familiar-gen-sql.ps1 from 09_beast.json
-- Do not hand-edit: change the JSON and regenerate.
--
-- amount = EffectBasePoints + 1 (DieSides=1). buff=0x80000000,
-- debuff=0x84000000 (NO_AURA_CANCEL | AURA_IS_DEBUFF). See generator header.
-- ============================================================================

-- STEP 1: spell_dbc — summon spells
DELETE FROM spell_dbc WHERE ID IN (102080, 102081, 102082, 102083, 102084, 102085, 102086, 102087, 102088, 102089);
REPLACE INTO spell_dbc (ID, Attributes, CastingTimeIndex, DurationIndex, RangeIndex, EquippedItemClass, Effect_1, EffectMiscValue_1, EffectMiscValueB_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS) VALUES
(102080, 262416, 1, 21, 1, -1, 28, 191080, 41, 32, 1, 1584, 'Summon Familiar: Раптор'),
(102081, 262416, 1, 21, 1, -1, 28, 191081, 41, 32, 1, 1584, 'Summon Familiar: Хромой Раптор'),
(102082, 262416, 1, 21, 1, -1, 28, 191082, 41, 32, 1, 3775, 'Summon Familiar: Полосатый Волчер'),
(102083, 262416, 1, 21, 1, -1, 28, 191083, 41, 32, 1, 3775, 'Summon Familiar: Тощий Волчер'),
(102084, 262416, 1, 21, 1, -1, 28, 191084, 41, 32, 1, 293, 'Summon Familiar: Тигрёнок'),
(102085, 262416, 1, 21, 1, -1, 28, 191085, 41, 32, 1, 293, 'Summon Familiar: Раненый Тигрёнок'),
(102086, 262416, 1, 21, 1, -1, 28, 191086, 41, 32, 1, 3896, 'Summon Familiar: Свирепый Медвежонок'),
(102087, 262416, 1, 21, 1, -1, 28, 191087, 41, 32, 1, 1585, 'Summon Familiar: Скорпиончик'),
(102088, 262416, 1, 21, 1, -1, 28, 191088, 41, 32, 1, 956, 'Summon Familiar: Волкус'),
(102089, 262416, 1, 21, 1, -1, 28, 191089, 41, 32, 1, 3891, 'Summon Familiar: Спектральный Зверь');

-- STEP 2: spell_dbc — positive owner-auras (103xxx, buff bar)
DELETE FROM spell_dbc WHERE ID IN (103080, 103081, 103082, 103083, 103084, 103085, 103086, 103087, 103088, 103089);
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103080, 2147483648, 21, 101, 1, -1, 6, 290, 0, 1, 0, 1, 1, 1584, 'Familiar Aura: Раптор', '+1% шанса критического удара');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103081, 2147483648, 21, 101, 1, -1, 6, 290, 0, 1, 0, 1, 1, 1584, 'Familiar Aura: Хромой Раптор', '+1% шанса критического удара');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103082, 2147483648, 21, 101, 1, -1, 6, 137, 1, 1, 0, 1, 1, 3775, 'Familiar Aura: Полосатый Волчер', '+2% силы');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103083, 2147483648, 21, 101, 1, -1, 6, 137, 1, 1, 0, 1, 1, 3775, 'Familiar Aura: Тощий Волчер', '+2% силы');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103084, 2147483648, 21, 101, 1, -1, 6, 49, 0, 1, 0, 1, 1, 293, 'Familiar Aura: Тигрёнок', '+1% уворота');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103085, 2147483648, 21, 101, 1, -1, 6, 49, 0, 1, 0, 1, 1, 293, 'Familiar Aura: Раненый Тигрёнок', '+1% уворота');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103086, 2147483648, 21, 101, 1, -1, 6, 137, 2, 1, 0, 1, 6, 49, 2, 1, 0, 1, 1, 3896, 'Familiar Aura: Свирепый Медвежонок', '+3% силы, +3% уворота');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103087, 2147483648, 21, 101, 1, -1, 6, 49, 2, 1, 0, 1, 6, 31, 4, 1, 0, 1, 1, 1585, 'Familiar Aura: Скорпиончик', '+3% уворота, +5% скорости передвижения');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103088, 2147483648, 21, 101, 1, -1, 6, 290, 2, 1, 0, 1, 6, 137, 2, 1, 0, 1, 1, 956, 'Familiar Aura: Волкус', '+3% шанса критического удара, +3% силы');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, Effect_3, EffectAura_3, EffectBasePoints_3, EffectDieSides_3, EffectMiscValue_3, ImplicitTargetA_3, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103089, 2147483648, 21, 101, 1, -1, 6, 290, 4, 1, 0, 1, 6, 137, 4, 1, 0, 1, 6, 192, 4, 1, 0, 1, 1, 3891, 'Familiar Aura: Спектральный Зверь', '+5% шанса критического удара, +5% силы, +5% скорости атаки');

-- STEP 3: spell_dbc — negative owner-auras (104xxx, debuff bar)
DELETE FROM spell_dbc WHERE ID IN (104081, 104083, 104085, 104089);
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(104081, 2214592512, 21, 101, 1, -1, 6, 137, -2, 1, 2, 1, 1, 1584, 'Familiar Debuff: Хромой Раптор', '-1% выносливости');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(104083, 2214592512, 21, 101, 1, -1, 6, 49, -2, 1, 0, 1, 1, 3775, 'Familiar Debuff: Тощий Волчер', '-1% уворота');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(104085, 2214592512, 21, 101, 1, -1, 6, 137, -2, 1, 2, 1, 1, 293, 'Familiar Debuff: Раненый Тигрёнок', '-1% выносливости');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(104089, 2214592512, 21, 101, 1, -1, 6, 137, -11, 1, 2, 1, 1, 3891, 'Familiar Debuff: Спектральный Зверь', '-10% выносливости');

-- STEP 4: creature_template + _model + _locale
DELETE FROM creature_template_locale WHERE entry IN (191080, 191081, 191082, 191083, 191084, 191085, 191086, 191087, 191088, 191089);
DELETE FROM creature_template_model  WHERE CreatureID IN (191080, 191081, 191082, 191083, 191084, 191085, 191086, 191087, 191088, 191089);
DELETE FROM creature_template        WHERE entry IN (191080, 191081, 191082, 191083, 191084, 191085, 191086, 191087, 191088, 191089);

REPLACE INTO creature_template (entry, name, subname, minlevel, maxlevel, faction, unit_class, type, family, npcflag, AIName) VALUES
(191080, 'Раптор', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191081, 'Хромой Раптор', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191082, 'Полосатый Волчер', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191083, 'Тощий Волчер', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191084, 'Тигрёнок', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191085, 'Раненый Тигрёнок', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191086, 'Свирепый Медвежонок', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191087, 'Скорпиончик', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191088, 'Волкус', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191089, 'Спектральный Зверь', '', 1, 1, 35, 1, 7, 0, 0, '');

INSERT INTO creature_template_model (CreatureID, Idx, CreatureDisplayID, DisplayScale, Probability, VerifiedBuild) VALUES
(191080, 0, 29807, 1.0, 1, 0),
(191081, 0, 29807, 1.0, 1, 0),
(191082, 0, 25384, 1.0, 1, 0),
(191083, 0, 25384, 1.0, 1, 0),
(191084, 0, 16942, 1.0, 1, 0),
(191085, 0, 16942, 1.0, 1, 0),
(191086, 0, 16189, 1.0, 1, 0),
(191087, 0, 2488, 1.0, 1, 0),
(191088, 0, 11412, 0.8, 1, 0),
(191089, 0, 30409, 1.0, 1, 0);

INSERT INTO creature_template_locale (entry, locale, Name, Title) VALUES
(191080, 'ruRU', 'Раптор', ''),
(191081, 'ruRU', 'Хромой Раптор', ''),
(191082, 'ruRU', 'Полосатый Волчер', ''),
(191083, 'ruRU', 'Тощий Волчер', ''),
(191084, 'ruRU', 'Тигрёнок', ''),
(191085, 'ruRU', 'Раненый Тигрёнок', ''),
(191086, 'ruRU', 'Свирепый Медвежонок', ''),
(191087, 'ruRU', 'Скорпиончик', ''),
(191088, 'ruRU', 'Волкус', ''),
(191089, 'ruRU', 'Спектральный Зверь', '');

-- STEP 5: item_template (scrolls) + _locale
DELETE FROM item_template_locale WHERE ID IN (110080, 110081, 110082, 110083, 110084, 110085, 110086, 110087, 110088, 110089) AND locale = 'ruRU';
DELETE FROM item_template        WHERE entry IN (110080, 110081, 110082, 110083, 110084, 110085, 110086, 110087, 110088, 110089);

REPLACE INTO item_template (entry, class, subclass, name, displayid, Quality, Flags, BuyPrice, SellPrice, InventoryType, AllowableClass, ItemLevel, RequiredLevel, MaxCount, stackable, spellid_1, spelltrigger_1, spellcharges_1, spellid_2, spelltrigger_2, spellcharges_2, bonding, description, Material) VALUES
(110080, 15, 2, 'Клетка с: Раптор', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102080, 6, 0, 1, 'Обучает призывать фамильяра: Раптор. +1% шанса критического удара', 4),
(110081, 15, 2, 'Клетка с: Хромой Раптор', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102081, 6, 0, 1, 'Обучает призывать фамильяра: Хромой Раптор. +1% шанса критического удара; -1% выносливости', 4),
(110082, 15, 2, 'Клетка с: Полосатый Волчер', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102082, 6, 0, 1, 'Обучает призывать фамильяра: Полосатый Волчер. +2% силы', 4),
(110083, 15, 2, 'Клетка с: Тощий Волчер', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102083, 6, 0, 1, 'Обучает призывать фамильяра: Тощий Волчер. +2% силы; -1% уворота', 4),
(110084, 15, 2, 'Клетка с: Тигрёнок', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102084, 6, 0, 1, 'Обучает призывать фамильяра: Тигрёнок. +1% уворота', 4),
(110085, 15, 2, 'Клетка с: Раненый Тигрёнок', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102085, 6, 0, 1, 'Обучает призывать фамильяра: Раненый Тигрёнок. +1% уворота; -1% выносливости', 4),
(110086, 15, 2, 'Клетка с: Свирепый Медвежонок', 58861, 3, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102086, 6, 0, 1, 'Обучает призывать фамильяра: Свирепый Медвежонок. +3% силы, +3% уворота', 4),
(110087, 15, 2, 'Клетка с: Скорпиончик', 58861, 3, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102087, 6, 0, 1, 'Обучает призывать фамильяра: Скорпиончик. +3% уворота, +5% скорости передвижения', 4),
(110088, 15, 2, 'Клетка с: Волкус', 58861, 3, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102088, 6, 0, 1, 'Обучает призывать фамильяра: Волкус. +3% шанса критического удара, +3% силы', 4),
(110089, 15, 2, 'Клетка с: Спектральный Зверь', 58861, 4, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102089, 6, 0, 1, 'Обучает призывать фамильяра: Спектральный Зверь. +5% шанса критического удара, +5% силы, +5% скорости атаки; -10% выносливости', 4);

INSERT INTO item_template_locale (ID, locale, Name, Description) VALUES
(110080, 'ruRU', 'Клетка с: Раптор', 'Обучает призывать фамильяра: Раптор. +1% шанса критического удара'),
(110081, 'ruRU', 'Клетка с: Хромой Раптор', 'Обучает призывать фамильяра: Хромой Раптор. +1% шанса критического удара; -1% выносливости'),
(110082, 'ruRU', 'Клетка с: Полосатый Волчер', 'Обучает призывать фамильяра: Полосатый Волчер. +2% силы'),
(110083, 'ruRU', 'Клетка с: Тощий Волчер', 'Обучает призывать фамильяра: Тощий Волчер. +2% силы; -1% уворота'),
(110084, 'ruRU', 'Клетка с: Тигрёнок', 'Обучает призывать фамильяра: Тигрёнок. +1% уворота'),
(110085, 'ruRU', 'Клетка с: Раненый Тигрёнок', 'Обучает призывать фамильяра: Раненый Тигрёнок. +1% уворота; -1% выносливости'),
(110086, 'ruRU', 'Клетка с: Свирепый Медвежонок', 'Обучает призывать фамильяра: Свирепый Медвежонок. +3% силы, +3% уворота'),
(110087, 'ruRU', 'Клетка с: Скорпиончик', 'Обучает призывать фамильяра: Скорпиончик. +3% уворота, +5% скорости передвижения'),
(110088, 'ruRU', 'Клетка с: Волкус', 'Обучает призывать фамильяра: Волкус. +3% шанса критического удара, +3% силы'),
(110089, 'ruRU', 'Клетка с: Спектральный Зверь', 'Обучает призывать фамильяра: Спектральный Зверь. +5% шанса критического удара, +5% силы, +5% скорости атаки; -10% выносливости');