-- ============================================================================
-- Nemesis Familiar Gacha — family 3 (Ледяной / ice)
-- AUTO-GENERATED by scripts/familiar-gen-sql.ps1 from 03_ice.json
-- Do not hand-edit: change the JSON and regenerate.
--
-- amount = EffectBasePoints + 1 (DieSides=1). buff=0x80000000,
-- debuff=0x84000000 (NO_AURA_CANCEL | AURA_IS_DEBUFF). See generator header.
-- ============================================================================

-- STEP 1: spell_dbc — summon spells
DELETE FROM spell_dbc WHERE ID IN (102020, 102021, 102022, 102023, 102024, 102025, 102026, 102027, 102028, 102029);
REPLACE INTO spell_dbc (ID, Attributes, CastingTimeIndex, DurationIndex, RangeIndex, EquippedItemClass, Effect_1, EffectMiscValue_1, EffectMiscValueB_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS) VALUES
(102020, 262416, 1, 21, 1, -1, 28, 191020, 41, 32, 1, 4074, 'Summon Familiar: Холодок'),
(102021, 262416, 1, 21, 1, -1, 28, 191021, 41, 32, 1, 4074, 'Summon Familiar: Маленький Холодок'),
(102022, 262416, 1, 21, 1, -1, 28, 191022, 41, 32, 1, 3911, 'Summon Familiar: Льдинка'),
(102023, 262416, 1, 21, 1, -1, 28, 191023, 41, 32, 1, 3911, 'Summon Familiar: Маленькая Льдинка'),
(102024, 262416, 1, 21, 1, -1, 28, 191024, 41, 32, 1, 2132, 'Summon Familiar: Иней'),
(102025, 262416, 1, 21, 1, -1, 28, 191025, 41, 32, 1, 2132, 'Summon Familiar: Подмёрзший Иней'),
(102026, 262416, 1, 21, 1, -1, 28, 191026, 41, 32, 1, 3073, 'Summon Familiar: Ледяной Сильф'),
(102027, 262416, 1, 21, 1, -1, 28, 191027, 41, 32, 1, 4094, 'Summon Familiar: Зимний Дух'),
(102028, 262416, 1, 21, 1, -1, 28, 191028, 41, 32, 1, 1700, 'Summon Familiar: Морозный Дракончик'),
(102029, 262416, 1, 21, 1, -1, 28, 191029, 41, 32, 1, 3752, 'Summon Familiar: Морозец');

-- STEP 2: spell_dbc — positive owner-auras (103xxx, buff bar)
DELETE FROM spell_dbc WHERE ID IN (103020, 103021, 103022, 103023, 103024, 103025, 103026, 103027, 103028, 103029);
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103020, 2147483648, 21, 101, 1, -1, 6, 79, 1, 1, 16, 1, 1, 4074, 'Familiar Aura: Холодок', '+2% урона морозом');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103021, 2147483648, 21, 101, 1, -1, 6, 79, 1, 1, 16, 1, 1, 4074, 'Familiar Aura: Маленький Холодок', '+2% урона морозом');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103022, 2147483648, 21, 101, 1, -1, 6, 22, 4, 1, 16, 1, 1, 3911, 'Familiar Aura: Льдинка', '+5 сопротивления морозу');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103023, 2147483648, 21, 101, 1, -1, 6, 22, 4, 1, 16, 1, 1, 3911, 'Familiar Aura: Маленькая Льдинка', '+5 сопротивления морозу');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103024, 2147483648, 21, 101, 1, -1, 6, 65, 1, 1, 0, 1, 1, 2132, 'Familiar Aura: Иней', '+2% скорости накладывания заклинаний');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103025, 2147483648, 21, 101, 1, -1, 6, 65, 1, 1, 0, 1, 1, 2132, 'Familiar Aura: Подмёрзший Иней', '+2% скорости накладывания заклинаний');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103026, 2147483648, 21, 101, 1, -1, 6, 79, 4, 1, 16, 1, 6, 65, 2, 1, 0, 1, 1, 3073, 'Familiar Aura: Ледяной Сильф', '+5% урона морозом, +3% скорости накладывания заклинаний');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103027, 2147483648, 21, 101, 1, -1, 6, 79, 4, 1, 16, 1, 6, 22, 4, 1, 16, 1, 1, 4094, 'Familiar Aura: Зимний Дух', '+5% урона морозом, +5 сопротивления морозу');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103028, 2147483648, 21, 101, 1, -1, 6, 57, 4, 1, 0, 1, 6, 137, 2, 1, 3, 1, 1, 1700, 'Familiar Aura: Морозный Дракончик', '+5% шанса критического удара заклинаний, +3% интеллекта');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, Effect_3, EffectAura_3, EffectBasePoints_3, EffectDieSides_3, EffectMiscValue_3, ImplicitTargetA_3, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(103029, 2147483648, 21, 101, 1, -1, 6, 79, 9, 1, 16, 1, 6, 137, 4, 1, 3, 1, 6, 22, 4, 1, 16, 1, 1, 3752, 'Familiar Aura: Морозец', '+10% урона морозом, +5% интеллекта, +5 сопротивления морозу');

-- STEP 3: spell_dbc — negative owner-auras (104xxx, debuff bar)
DELETE FROM spell_dbc WHERE ID IN (104021, 104023, 104025, 104029);
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(104021, 2214592512, 21, 101, 1, -1, 6, 22, -2, 1, 4, 1, 1, 4074, 'Familiar Debuff: Маленький Холодок', '-1 сопротивления огню');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(104023, 2214592512, 21, 101, 1, -1, 6, 31, -2, 1, 0, 1, 1, 3911, 'Familiar Debuff: Маленькая Льдинка', '-1% скорости передвижения');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(104025, 2214592512, 21, 101, 1, -1, 6, 137, -2, 1, 3, 1, 1, 2132, 'Familiar Debuff: Подмёрзший Иней', '-1% интеллекта');
REPLACE INTO spell_dbc (ID, Attributes, DurationIndex, ProcChance, RangeIndex, EquippedItemClass, Effect_1, EffectAura_1, EffectBasePoints_1, EffectDieSides_1, EffectMiscValue_1, ImplicitTargetA_1, Effect_2, EffectAura_2, EffectBasePoints_2, EffectDieSides_2, EffectMiscValue_2, ImplicitTargetA_2, SchoolMask, SpellIconID, Name_Lang_enUS, Description_Lang_enUS) VALUES
(104029, 2214592512, 21, 101, 1, -1, 6, 22, -11, 1, 4, 1, 6, 137, -6, 1, 2, 1, 1, 3752, 'Familiar Debuff: Морозец', '-10 сопротивления огню, -5% выносливости');

-- STEP 4: creature_template + _model + _locale
DELETE FROM creature_template_locale WHERE entry IN (191020, 191021, 191022, 191023, 191024, 191025, 191026, 191027, 191028, 191029);
DELETE FROM creature_template_model  WHERE CreatureID IN (191020, 191021, 191022, 191023, 191024, 191025, 191026, 191027, 191028, 191029);
DELETE FROM creature_template        WHERE entry IN (191020, 191021, 191022, 191023, 191024, 191025, 191026, 191027, 191028, 191029);

REPLACE INTO creature_template (entry, name, subname, minlevel, maxlevel, faction, unit_class, type, family, npcflag, AIName) VALUES
(191020, 'Холодок', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191021, 'Маленький Холодок', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191022, 'Льдинка', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191023, 'Маленькая Льдинка', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191024, 'Иней', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191025, 'Подмёрзший Иней', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191026, 'Ледяной Сильф', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191027, 'Зимний Дух', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191028, 'Морозный Дракончик', '', 1, 1, 35, 1, 7, 0, 0, ''),
(191029, 'Морозец', '', 1, 1, 35, 1, 7, 0, 0, '');

INSERT INTO creature_template_model (CreatureID, Idx, CreatureDisplayID, DisplayScale, Probability, VerifiedBuild) VALUES
(191020, 0, 26452, 1.0, 1, 0),
(191021, 0, 26452, 1.0, 1, 0),
(191022, 0, 28216, 1.0, 1, 0),
(191023, 0, 28216, 1.0, 1, 0),
(191024, 0, 65024, 1.0, 1, 0),
(191025, 0, 65025, 1.0, 1, 0),
(191026, 0, 15671, 1.0, 1, 0),
(191027, 0, 19033, 1.0, 1, 0),
(191028, 0, 6293, 1.0, 1, 0),
(191029, 0, 28456, 1.0, 1, 0);

INSERT INTO creature_template_locale (entry, locale, Name, Title) VALUES
(191020, 'ruRU', 'Холодок', ''),
(191021, 'ruRU', 'Маленький Холодок', ''),
(191022, 'ruRU', 'Льдинка', ''),
(191023, 'ruRU', 'Маленькая Льдинка', ''),
(191024, 'ruRU', 'Иней', ''),
(191025, 'ruRU', 'Подмёрзший Иней', ''),
(191026, 'ruRU', 'Ледяной Сильф', ''),
(191027, 'ruRU', 'Зимний Дух', ''),
(191028, 'ruRU', 'Морозный Дракончик', ''),
(191029, 'ruRU', 'Морозец', '');

-- muted-ambient custom displays (need rows in patched CreatureDisplayInfo.dbc, server+client)
DELETE FROM creature_model_info WHERE DisplayID IN (65024, 65025);
INSERT INTO creature_model_info (DisplayID, BoundingRadius, CombatReach, Gender, DisplayID_Other_Gender)
SELECT 65024, BoundingRadius, CombatReach, Gender, 0 FROM creature_model_info WHERE DisplayID = 31722;
INSERT INTO creature_model_info (DisplayID, BoundingRadius, CombatReach, Gender, DisplayID_Other_Gender)
SELECT 65025, BoundingRadius, CombatReach, Gender, 0 FROM creature_model_info WHERE DisplayID = 31722;

-- STEP 5: item_template (scrolls) + _locale
DELETE FROM item_template_locale WHERE ID IN (110020, 110021, 110022, 110023, 110024, 110025, 110026, 110027, 110028, 110029) AND locale = 'ruRU';
DELETE FROM item_template        WHERE entry IN (110020, 110021, 110022, 110023, 110024, 110025, 110026, 110027, 110028, 110029);

REPLACE INTO item_template (entry, class, subclass, name, displayid, Quality, Flags, BuyPrice, SellPrice, InventoryType, AllowableClass, ItemLevel, RequiredLevel, MaxCount, stackable, spellid_1, spelltrigger_1, spellcharges_1, spellid_2, spelltrigger_2, spellcharges_2, bonding, description, Material) VALUES
(110020, 15, 2, 'Клетка с: Холодок', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102020, 6, 0, 1, 'Обучает призывать фамильяра: Холодок. +2% урона морозом', 4),
(110021, 15, 2, 'Клетка с: Маленький Холодок', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102021, 6, 0, 1, 'Обучает призывать фамильяра: Маленький Холодок. +2% урона морозом; -1 сопротивления огню', 4),
(110022, 15, 2, 'Клетка с: Льдинка', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102022, 6, 0, 1, 'Обучает призывать фамильяра: Льдинка. +5 сопротивления морозу', 4),
(110023, 15, 2, 'Клетка с: Маленькая Льдинка', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102023, 6, 0, 1, 'Обучает призывать фамильяра: Маленькая Льдинка. +5 сопротивления морозу; -1% скорости передвижения', 4),
(110024, 15, 2, 'Клетка с: Иней', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102024, 6, 0, 1, 'Обучает призывать фамильяра: Иней. +2% скорости накладывания заклинаний', 4),
(110025, 15, 2, 'Клетка с: Подмёрзший Иней', 58861, 1, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102025, 6, 0, 1, 'Обучает призывать фамильяра: Подмёрзший Иней. +2% скорости накладывания заклинаний; -1% интеллекта', 4),
(110026, 15, 2, 'Клетка с: Ледяной Сильф', 58861, 3, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102026, 6, 0, 1, 'Обучает призывать фамильяра: Ледяной Сильф. +5% урона морозом, +3% скорости накладывания заклинаний', 4),
(110027, 15, 2, 'Клетка с: Зимний Дух', 58861, 3, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102027, 6, 0, 1, 'Обучает призывать фамильяра: Зимний Дух. +5% урона морозом, +5 сопротивления морозу', 4),
(110028, 15, 2, 'Клетка с: Морозный Дракончик', 58861, 3, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102028, 6, 0, 1, 'Обучает призывать фамильяра: Морозный Дракончик. +5% шанса критического удара заклинаний, +3% интеллекта', 4),
(110029, 15, 2, 'Клетка с: Морозец', 58861, 4, 64, 0, 1000000, 0, -1, 1, 1, 0, 1, 55884, 0, -1, 102029, 6, 0, 1, 'Обучает призывать фамильяра: Морозец. +10% урона морозом, +5% интеллекта, +5 сопротивления морозу; -10 сопротивления огню, -5% выносливости', 4);

INSERT INTO item_template_locale (ID, locale, Name, Description) VALUES
(110020, 'ruRU', 'Клетка с: Холодок', 'Обучает призывать фамильяра: Холодок. +2% урона морозом'),
(110021, 'ruRU', 'Клетка с: Маленький Холодок', 'Обучает призывать фамильяра: Маленький Холодок. +2% урона морозом; -1 сопротивления огню'),
(110022, 'ruRU', 'Клетка с: Льдинка', 'Обучает призывать фамильяра: Льдинка. +5 сопротивления морозу'),
(110023, 'ruRU', 'Клетка с: Маленькая Льдинка', 'Обучает призывать фамильяра: Маленькая Льдинка. +5 сопротивления морозу; -1% скорости передвижения'),
(110024, 'ruRU', 'Клетка с: Иней', 'Обучает призывать фамильяра: Иней. +2% скорости накладывания заклинаний'),
(110025, 'ruRU', 'Клетка с: Подмёрзший Иней', 'Обучает призывать фамильяра: Подмёрзший Иней. +2% скорости накладывания заклинаний; -1% интеллекта'),
(110026, 'ruRU', 'Клетка с: Ледяной Сильф', 'Обучает призывать фамильяра: Ледяной Сильф. +5% урона морозом, +3% скорости накладывания заклинаний'),
(110027, 'ruRU', 'Клетка с: Зимний Дух', 'Обучает призывать фамильяра: Зимний Дух. +5% урона морозом, +5 сопротивления морозу'),
(110028, 'ruRU', 'Клетка с: Морозный Дракончик', 'Обучает призывать фамильяра: Морозный Дракончик. +5% шанса критического удара заклинаний, +3% интеллекта'),
(110029, 'ruRU', 'Клетка с: Морозец', 'Обучает призывать фамильяра: Морозец. +10% урона морозом, +5% интеллекта, +5 сопротивления морозу; -10 сопротивления огню, -5% выносливости');